### ISSUE TITLE
Unable to brew install

### ISSUE THREAD

**Issue by SamGoody** [frescobaldi/frescobaldi#1026]
When installing frescobaldi, get:
```
Error: SHA256 mismatch
Expected: 9d6dfe7530c26d6062fb370fbb068bb554d9c3ed0b82dc640c362fdc62ca0947
Actual: c6903c4b6ab71730ae2a1da9fb95830a83da82185b5ef6b8184b16c0cae908ba
```

I downloaded poplar https://github.com/wbsoft/python-poppler-qt4/archive/v0.18.1.tar.gz  and can verify that the sha256 hash is c6903c...

**Comment by marnen** [comment]
I no longer maintain the Homebrew package; the recommended way to install on Mac OS now is to use one of the binary releases. If for some reason you can't do that, let me know and I'll see if I can help.

**Comment by dliessi** [comment]
This issue is obsolete, since Homebrew's Frescobaldi is currently a cask installing our prebuilt application bundle.
