### ISSUE TITLE
Some Japanese fonts are not displayed

### ISSUE THREAD

**Issue by marnen** [frescobaldi/frescobaldi#1058]
I'm using Frescobaldi 2.20.0 from the prebuilt Mac application bundle on Mac OS X 10.13 (High Sierra). Most Japanese fonts do not display in the PDF viewer (they do display in the editor, and when I view the PDF files with other PDF utilities, I can see the Japanese text).

I believe that this may be related to https://bugs.freedesktop.org/show_bug.cgi?id=7093; the suggested fix there seems to be to install poppler-data. How do we get this into the application build?

**Comment by uliska** [comment]
Could you please post an example PDF?

**Comment by marnen** [comment]
@uliska Sorry, should have done that in the first place! Here you are.
[japanese-font-handling.pdf](https://github.com/wbsoft/frescobaldi/files/1725830/japanese-font-handling.pdf)

**Comment by marnen** [comment]
Meanwhile, for this file, I was able to get the Japanese lyrics to show up in Fresco—but only in certain fonts.
[score.pdf](https://github.com/wbsoft/frescobaldi/files/1725836/score.pdf)

**Comment by tinbotu** [comment]
same problem.
Japanese text with OpenType (or CID PS Outline) fonts can't seem to be previewed on frescobaldi. It's does not depend on Windows or macos.

The PDF output by lilypond are OK for Acrobat, Apple Preview, Chrome, etc.

I don't know much about fonts, gs,.. but this is troubled me too. I wish happy to contribute about it  *test* or whatnot.

|font-name  |type   |foundry|music view|PDF  |
|:--|--|--|--|--|
|A-OTF Ryumin Pro Regular|otf|Morisawa|NG (unshown)|OK|
|Kozuka Gothic Pr6N|otf|Adobe|NG (unshown)|OK|
|Hiragino Mincho ProN W3|otf|Apple|NG (unshown)|OK|
|MS Gothic|ttc|Microsoft|OK|OK|
|MS Mincho|ttc|Microsoft|OK|OK|
|Meiryo|ttc|Microsoft|OK|OK|
|HGSoeiKakupoptai|ttc|Microsoft|OK|OK|
|Noto Serif JP Regular|otf|Google|NG (garbled)|NG (garbled)|

![japanese-fonts-test-win](https://user-images.githubusercontent.com/666730/37722036-6adfc0f6-2d6e-11e8-9f15-a27337ff92fa.png)
![japanese-fonts-test-mac](https://user-images.githubusercontent.com/666730/37722035-6a44fdfa-2d6e-11e8-8750-90a0cc248bc1.png)


This is pdf, `ly` is below:
[japanese-fonts-test-mac-small.pdf](https://github.com/wbsoft/frescobaldi/files/1834138/japanese-fonts-test-mac-small.pdf)

`japanese-fonts-test-mac-small.ly`

```ly:japanese-fonts-test-mac-small.ly
\version "2.19.80"

\markup{
  \left-column{
  \roman{"default"}
  "あのイーハトーヴォのすきとおった風、夏でも底に冷たさをもつ青いそら、うつくしい森で飾られたモリーオ市、郊外のぎらぎらひかる草の波。"

  \vspace #1
  \roman{"Hiragino Mincho ProN W6"}
  \override #'(font-name . "Hiragino Mincho ProN W6")
  "あのイーハトーヴォのすきとおった風、夏でも底に冷たさをもつ青いそら、うつくしい森で飾られたモリーオ市、郊外のぎらぎらひかる草の波。"
  }
}

```


**version**

- Frescobaldi 3.0.0 (Windows installer)
- Frescobaldi 2.20-0-x86_64.dmg (macOS)

**OS / Environment**

- Lilypond Windows 2.19.80 (binary from official site)
- Lilypond Windows 2.18.2 (binary from official site)
- Lilypond macOS x86; LilyPond 2.19.81 (from homebrew caskroom lilypond-dev)
- Lilypond macOS x86; LilyPond 2.18.2-1 (binary from official site)

**Comment by fedelibre** [comment]
> I believe that this may be related to https://bugs.freedesktop.org/show_bug.cgi?id=7093; the suggested fix there seems to be to install poppler-data.

Yes, it seems to be the solution. I'm on Linux (Fedora) and I see that the RPM package renders the file fine, while the flatpak package doesn't. I'm going to fix the flatpak package of Frescobaldi.

The problem remains with Windows and Mac installers.

**Comment by lamusique** [comment]
> The problem remains with Windows and Mac installers.
@fedelibre I use Frescobaldi installed from Homebrew and it's not fixed. Is it possible to fix it?

**Comment by marnen** [comment]
@lamusique I don’t know if the Fresco Homebrew formula is still maintained (perhaps someone else does). I know that I used to maintain that formula, but stopped maintaining or recommending its use once binaries became available. Have you tried installing one of the binaries?

**Comment by fedelibre** [comment]
@marnen See my comment on 26/12/2023. I  don't think that the problem is fixed in the binaries.

Let's hope that the Qt6 port (which drops python-poppler-qt) would land in master quite soon, even though I don't know what's the status.

**Comment by marnen** [comment]
@fedelibre I don’t know the current state of the binaries either, since Fresco 3 has never worked right on Mac OS for me (although looking again at things like #986, I may have to try again). But I’m skeptical that the Homebrew formula is being maintained at all since I quit supporting it; is it?
