### ISSUE TITLE
Questions about the Show Available Fonts dialog

### ISSUE THREAD

**Issue by uliska** [frescobaldi/frescobaldi#1076]
This is related to #1075.

I just moved the "show available fonts" dialog to its own module because I think it's too heavy to be squeezed into the `engrave.lytools` module.

As a consequence I would also move its actions out of the `engrave` module completely, because apart from the fact that it starts LilyPond it is completely unrelated to "engraving".

In fact I would even suggest to move the menu entry from `LilyPond` to `Tools`, maybe at the end of the group with Pitch, Rhythm etc. The idea behind this is that I thought that once the display situation is improved this dialog could receive some additional functionality, for example generating font selection code, either "locally" or as a general document-wide font setting.

What do you think about these ideas?

**Comment by uliska** [comment]
Well, I can do that quickly and still wait for Wilbert and/or Peter to comment on. But I won't go for the code generation right now.

**Comment by dliessi** [comment]
I agree with @fedelibre.

**Comment by uliska** [comment]
Obsolete
