### ISSUE TITLE
structure should ignore commands mentioned in commented lines

### ISSUE THREAD

**Issue by fedelibre** [frescobaldi/frescobaldi#1081]
As you can see in the below screenshot, the Structure tool picks up also the commands present in a commented line.
I guess it should ignore commented commands as they are not active and sometimes just mentioned for the sake of remembering something, as in this example:

![structure comments](https://user-images.githubusercontent.com/1644647/43013612-c44f5c8e-8c49-11e8-9bab-1e9f42a2f496.png)

In this case \bookpart should **not** appear in the Structure pane.

**Comment by PeterBjuhr** [comment]
@fedelibre you could try this in the outline pattern in the tools preferences:
`^[^%]+(?P<title>\\(score|book|bookpart))\b` 
It seems to work, but I don't know yet if it's the best approach and if it should be before all lines?

**Comment by fedelibre** [comment]
I've replaced the first regexp in the tools preference with yours and I confirm that it solves the problem... but it breaks outline. Maybe I did something wrong.

I didn't know the outline was made with regexp matching. I thought it was more sophisticated and use some kind of lilypond syntax parser.

**Comment by PeterBjuhr** [comment]
How does it break outline? I've looked at a couple of files but I can't see anything wrong (but I haven't used the tool before so I may be missing something).

Yeah, I agree the solution seem a little bit naive when we have a Lilypond parser.

**Comment by fedelibre** [comment]
Here's how a file looks by default:
![outline-default](https://user-images.githubusercontent.com/1644647/204163899-af9d9710-f92e-41f2-8eeb-647b21da13d0.png)

After changing the first regexp in the Tools preferences, all the book, bookpart and score occurrences disappear from the outline:

![outline-changed](https://user-images.githubusercontent.com/1644647/204163986-bdefc3c8-2441-4e52-a2ba-a631beb3a09d.png)

**Comment by PeterBjuhr** [comment]
Could you attach the full file and I'll take a look.

**Comment by fedelibre** [comment]
It's here:
https://github.com/MutopiaProject/MutopiaProject/blob/master/ftp/BachJS/BWV208/Sheep/Sheep.ly

**Comment by PeterBjuhr** [comment]
Ok, I see the problem. `MULTILINE` mode is being used.

**Comment by PeterBjuhr** [comment]
I have done a suggestion in the PR above. It prevents matches in all "inactive" code (commented out code). 

But I'm concerned about certain keywords like "FIXME" that I can easily imagine preferably is located in a comment.

**Comment by dliessi** [comment]
The regex `^[^%\n]*(?P<title>\\(score|book|bookpart))\b` seems to behave as @fedelibre wanted, although only for single line comments.

**Comment by PeterBjuhr** [comment]
> you could try this in the outline pattern in the tools preferences:
^[^%]+(?P<title>\\(score|book|bookpart))\b

I realized that I had mistakenly written `+` instead of `*` in the regex above. But looking at the example file I also realized that block comments had to be taken into account.
