### ISSUE TITLE
File names in document tabs are not shown correctly on Mac

### ISSUE THREAD

**Issue by dliessi** [frescobaldi/frescobaldi#1087]
The file name in the pictures below is `common.ily`.
Compare current `master` (PyQt5)
![image](https://user-images.githubusercontent.com/5209500/43686665-f2c1af7c-98c9-11e8-84af-f9cb31b16ace.png)
with current branch `v2.x` (PyQt4)
![image](https://user-images.githubusercontent.com/5209500/43686668-0df86b3c-98ca-11e8-86d5-cfca8f65435e.png)
As you can see there are two problems: the file name is cut and there is extra space after the name.

**Comment by uliska** [comment]
Please checkout `debug/tab-text`

**Comment by dliessi** [comment]
> What does the tooltip over the tab show?

It shows the directory where the file is (unless it is a new unsaved file, in which case there is no tooltip).

> Please checkout debug/tab-text

I opened Frescobaldi, and opened and closed the file `common.ily`
Here is the output:

```
$ python3.6 frescobaldi
setDocumentStatus
Document name before replacing: Senza nome
Document name after replacing: Senza nome
Current/previouso tabText: 
setDocumentStatus
Document name before replacing: Senza nome
Document name after replacing: Senza nome
Current/previouso tabText: Senza nome
setDocumentStatus
Document name before replacing: Senza nome
Document name after replacing: Senza nome
Current/previouso tabText: Senza nome
setDocumentStatus
Document name before replacing: common.ily
Document name after replacing: common.ily
Current/previouso tabText: Senza nome
setDocumentStatus
Document name before replacing: Senza nome
Document name after replacing: Senza nome
Current/previouso tabText: 
$ 
```

**Comment by uliska** [comment]
This looks correct, which means that at the time when we use `setTabText()` the content of that tab's title is correct.

Could you please take the time and create a minimal example for this too? I'd like to get closer to determining if the issue is anywhere in our code or a Qt problem.

**Comment by dliessi** [comment]
> Could you please take the time and create a minimal example for this too?

I'll try, but not today... 😅
The other minimal example took several hours of work.
I don't really know how (Py)Qt works in detail, so instead of writing an example from scratch trying to reproduce the problem, I took the whole Frescobaldi and started to remove pieces.
The process was time consuming, since the various modules in `frescobaldi_app` have several inter-dependencies.

**Comment by dliessi** [comment]
Anyway, this is just a cosmetic issue: the high priority issue is #1073, and I'd say that #1086 is still higher than the present one (although related only to development work).

**Comment by dliessi** [comment]
The following is a minimal example, exhibiting all the characteristics of tabs in Frescobaldi (title, icon, cross to close the tab).
Copy `text-plain.svg` from [`frescobaldi_app/icons/TangoExt/scalable`](https://github.com/wbsoft/frescobaldi/tree/master/frescobaldi_app/icons/TangoExt/scalable) to the directory containing the script.

```
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import (QMainWindow, QVBoxLayout, QWidget, QApplication, QTabBar)
from PyQt5.QtGui import QIcon

qApp = QApplication([])
win = QMainWindow()

win.tabBar = QTabBar(win)
win.tabBar.setExpanding(False)
win.tabBar.setElideMode(Qt.ElideNone)
win.tabBar.setTabsClosable(True)
win.tabBar.addTab(QIcon('text-plain.svg'), 'Untitled')

layout = QVBoxLayout()
layout.addWidget(win.tabBar)

mainwidget = QWidget()
win.setCentralWidget(mainwidget)
mainwidget.setLayout(layout)

win.show()
qApp.exec_()
```

The problems with PyQt5 are the following:

- the text is cut, hiding approximately the first and the last letters,
- there is too much space between the cross and the icon,
- there appears to be the same amount of space at the two sides of the text (ignoring the cross and the icon), resulting in too much space from the text to the right margin.

Removing either the icon or the cross (commenting the `setTabClosable` line), which are however needed in Frescobaldi, results in the text being shown entirely, but there is still too much space after the text.

**Comment by dliessi** [comment]
I posted this example at [PyQt's mailing list](https://www.riverbankcomputing.com/pipermail/pyqt/2020-March/042612.html).
