### ISSUE TITLE
segmentation fault when closing the application by clicking on the X icon of the main bar

### ISSUE THREAD

**Issue by fedelibre** [frescobaldi/frescobaldi#1120]
I'm testing the Git menu and I'm getting crashes (core dumps) every time I agree on restarting Frescobaldi to enable the new checked-out branch (the checkout works correctly). Frescobaldi is not restarted.

The command I'm currently using is the second (uncommented):

```
$ cat .local/bin/frescobaldi 
#!/bin/bash
#PYTHONPATH=~/src/python-ly:$PYTHONPATH python3 ~/src/frescobaldi/frescobaldi $@
python3 ~/src/frescobaldi/frescobaldi --python-ly ~/src/python-ly $@
```

Interestingly, when I use the first command with PYTHONPATH variable, I get a core dump as well, but Frescobaldi is restarted successfully.

Here's the stack trace (find attached the  [binary core dump](https://github.com/wbsoft/frescobaldi/files/2479066/frescobaldi-git-restart-crash-dump.zip)):

```
$ coredumpctl dump --output frescobaldi-git-restart-crash.dump
           PID: 20715 (python3)
           UID: 1000 (fede)
           GID: 1000 (fede)
        Signal: 11 (SEGV)
     Timestamp: Mon 2018-10-15 15:06:15 CEST (40min ago)
  Command Line: python3 /home/fede/src/frescobaldi/frescobaldi --python-ly /home/fede/src/python-ly
    Executable: /usr/bin/python3.6
 Control Group: /user.slice/user-1000.slice/user@1000.service/gnome-terminal-server.service
          Unit: user@1000.service
     User Unit: gnome-terminal-server.service
         Slice: user-1000.slice
     Owner UID: 1000 (fede)
       Boot ID: 59d9549afdd54cda85274d62a464dfa8
    Machine ID: 632206f23825416c9521585b3569c6c4
      Hostname: federico
       Storage: /var/lib/systemd/coredump/core.python3.1000.59d9549afdd54cda85274d62a464dfa8.20715.1539608775000000.lz4
       Message: Process 20715 (python3) of user 1000 dumped core.
                
                Stack trace of thread 20717:
                #0  0x00007f7e980b35d8 _int_malloc (libc.so.6)
                #1  0x00007f7e980b556a malloc (libc.so.6)
                #2  0x00007f7e891be74f _xcb_in_read (libxcb.so.1)
                #3  0x00007f7e891bc305 _xcb_conn_wait (libxcb.so.1)
                #4  0x00007f7e891bdcaa xcb_wait_for_event (libxcb.so.1)
                #5  0x00007f7e86d845a9 _ZN15QXcbEventReader3runEv (libQt5XcbQpa.so.5)
                #6  0x00007f7e9015db4b _ZN14QThreadPrivate5startEPv (libQt5Core.so.5)
                #7  0x00007f7e98b92594 start_thread (libpthread.so.0)
                #8  0x00007f7e9812ae6f __clone (libc.so.6)
                
                Stack trace of thread 20718:
                #0  0x00007f7e981203e9 __poll (libc.so.6)
                #1  0x00007f7e8d072bc6 g_main_context_iterate.isra.21 (libglib-2.0.so.0)
                #2  0x00007f7e8d072cf0 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f7e7a4bae4d dconf_gdbus_worker_thread (libdconfsettings.so)
                #4  0x00007f7e8d09af8a g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007f7e98b92594 start_thread (libpthread.so.0)
                #6  0x00007f7e9812ae6f __clone (libc.so.6)
                
                Stack trace of thread 20721:
                #0  0x00007f7e981203e9 __poll (libc.so.6)
                #1  0x00007f7e8d072bc6 g_main_context_iterate.isra.21 (libglib-2.0.so.0)
                #2  0x00007f7e8d072cf0 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f7e9033e293 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #4  0x00007f7e902ecb7b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #5  0x00007f7e901546b6 _ZN7QThread4execEv (libQt5Core.so.5)
                #6  0x00007f7e86a7b7b9 _ZN22QDBusConnectionManager3runEv (libQt5DBus.so.5)
                #7  0x00007f7e9015db4b _ZN14QThreadPrivate5startEPv (libQt5Core.so.5)
                #8  0x00007f7e98b92594 start_thread (libpthread.so.0)
                #9  0x00007f7e9812ae6f __clone (libc.so.6)
                
                Stack trace of thread 20715:
                #0  0x00007f7e98b9851c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f7e891bc252 _xcb_conn_wait (libxcb.so.1)
                #2  0x00007f7e891bd9bf wait_for_reply (libxcb.so.1)
                #3  0x00007f7e891bdad6 xcb_wait_for_reply (libxcb.so.1)
                #4  0x00007f7e86d93018 _ZNK10QXcbScreen10topLevelAtERK6QPoint (libQt5XcbQpa.so.5)
                #5  0x00007f7e8ab731ed _ZN15QGuiApplication10topLevelAtERK6QPoint (libQt5Gui.so.5)
                #6  0x00007f7e880b4e0d _ZN12QApplication10topLevelAtERK6QPoint (libQt5Widgets.so.5)
                #7  0x00007f7e880b59da _ZN12QApplication8widgetAtERK6QPoint (libQt5Widgets.so.5)
                #8  0x00007f7e880bd4a0 _ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Eb (libQt5Widgets.so.5)
                #9  0x00007f7e88110723 _ZN13QWidgetWindow16handleMouseEventEP11QMouseEvent (libQt5Widgets.so.5)
                #10 0x00007f7e88112f0e _ZN13QWidgetWindow5eventEP6QEvent (libQt5Widgets.so.5)
                #11 0x00007f7e880b6475 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #12 0x00007f7e880bdb90 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #13 0x00007f7e8872f23e _ZN15sipQApplication6notifyEP7QObjectP6QEvent (QtWidgets.so)
                #14 0x00007f7e902edc36 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                #15 0x00007f7e8ab78f43 _ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE (libQt5Gui.so.5)
                #16 0x00007f7e8ab7b085 _ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE (libQt5Gui.so.5)
                #17 0x00007f7e8ab5646b _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5)
                #18 0x00007f7e86e177cf _ZN22QPAEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5XcbQpa.so.5)
                #19 0x00007f7e902ecb7b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #20 0x00007f7e902f4c46 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                #21 0x00007f7e8872dc7f meth_QApplication_exec_ (QtWidgets.so)
                #22 0x00007f7e98f1d942 _PyCFunction_FastCallDict (libpython3.6m.so.1.0)
                #23 0x00007f7e98f2cbdd call_function (libpython3.6m.so.1.0)
                #24 0x00007f7e98f5d12a _PyEval_EvalFrameDefault (libpython3.6m.so.1.0)
                #25 0x00007f7e98ee4d5a fast_function (libpython3.6m.so.1.0)
                #26 0x00007f7e98f2ccc2 call_function (libpython3.6m.so.1.0)
                #27 0x00007f7e98f5d12a _PyEval_EvalFrameDefault (libpython3.6m.so.1.0)
                #28 0x00007f7e98f2f058 PyEval_EvalCodeEx (libpython3.6m.so.1.0)
                #29 0x00007f7e98f2ff0b PyEval_EvalCode (libpython3.6m.so.1.0)
                #30 0x00007f7e98fc97f2 run_mod (libpython3.6m.so.1.0)
                #31 0x00007f7e98fcb3ca PyRun_FileExFlags (libpython3.6m.so.1.0)
                #32 0x00007f7e98fcc128 PyRun_SimpleFileExFlags (libpython3.6m.so.1.0)
                #33 0x00007f7e98fcd1fe Py_Main (libpython3.6m.so.1.0)
                #34 0x000055ffd06d0ca8 main (python3.6)
                #35 0x00007f7e9805411b __libc_start_main (libc.so.6)
                #36 0x000055ffd06d0e1a _start (python3.6)
                
                Stack trace of thread 20720:
                #0  0x00007f7e981203e9 __poll (libc.so.6)
                #1  0x00007f7e8d072bc6 g_main_context_iterate.isra.21 (libglib-2.0.so.0)
                #2  0x00007f7e8d072f82 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007f7e811a57aa gdbus_shared_thread_func (libgio-2.0.so.0)
                #4  0x00007f7e8d09af8a g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007f7e98b92594 start_thread (libpthread.so.0)
                #6  0x00007f7e9812ae6f __clone (libc.so.6)
                
                Stack trace of thread 20725:
                #0  0x00007f7e98b9851c pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007f7e69a572d3 util_queue_thread_func (nouveau_dri.so)
                #2  0x00007f7e69a56feb impl_thrd_routine (nouveau_dri.so)
                #3  0x00007f7e98b92594 start_thread (libpthread.so.0)
                #4  0x00007f7e9812ae6f __clone (libc.so.6)
                
                Stack trace of thread 20719:
                #0  0x00007f7e981203e9 __poll (libc.so.6)
                #1  0x00007f7e8d072bc6 g_main_context_iterate.isra.21 (libglib-2.0.so.0)
                #2  0x00007f7e8d072cf0 g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007f7e8d072d41 glib_worker_main (libglib-2.0.so.0)
                #4  0x00007f7e8d09af8a g_thread_proxy (libglib-2.0.so.0)
                #5  0x00007f7e98b92594 start_thread (libpthread.so.0)
                #6  0x00007f7e9812ae6f __clone (libc.so.6)
```

**Comment by fedelibre** [comment]
If you unzip the attachment I sent previously and run this command:

```
$ file frescobaldi-git-restart-crash.dump 
frescobaldi-git-restart-crash.dump: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'python3 /home/fede/src/frescobaldi/frescobaldi --python-ly /home/fede/src/pytho', real uid: 1000, effective uid: 1000, real gid: 1000, effective gid: 1000, execfn: '/usr/bin/python3', platform: 'x86_64'
```

you see that the command seems truncated...

this does not occur when I use PYTHONPATH:

```
$ file fresco-2.dump 
fresco-2.dump: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'python3 /home/fede/src/frescobaldi/frescobaldi', real uid: 1000, effective uid: 1000, real gid: 1000, effective gid: 1000, execfn: '/usr/bin/python3', platform: 'x86_64'
```

Don't know if it matters...

**Comment by uliska** [comment]
I'm sorry, this is really foreign language to me ...

Just to be clear: This does *not* happen when you close and start Frescobaldi after having switched branches?

And: I assume there's no impact of *which* branch you switch to *which*?

**Comment by fedelibre** [comment]
> Just to be clear: This does _not_ happen when you close and start Frescobaldi after having switched branches?

Good point: it does happen even if I close Frescobaldi. I'm updating the title.
I'll try to do a better debug tomorrow.

Can you reproduce it or it's just me?

**Comment by uliska** [comment]
I have never experienced anything like this. What I *do* have is crashes when Frescobaldi tries to load a Python module that has been modified in the meantime, but that doesn't look like the errors you show.

**Comment by fedelibre** [comment]
I'm checking anything that might trigger the problem:

- it happens on both Wayland and Xorg
- I've removed all the *.pyc files with `git clean -d -x -f`, but this does not solve the issue

It might depend on the python version?
I'm using version 3.6.6.

**Comment by uliska** [comment]
So just to be clear: This is a permanent error and occurs *everytime* you close Frescobaldi through the `X`?

I still don't know too much about these things, but for me it looks like the crash happens through an interaction between (Py)Qt and the desktop environment/window manager/graphics server. I'd be pretty sure this isn't an actual bug in Frescobaldi's code.

Do you think you could identify other applications running on PyQt5 and test these? Maybe it's a hidden bug in (Py)Qt that only appears if the application object or mainwindow object is configured in a certain way.

Another, more direct way would be to ask about the crash on a Qt forum or maybe an appropriate stackexchange site. I'd assume *Qt* people might understand more from the core dumps you provided, and they might point us to submitting a proper bug report or to doing a workaround.

**Comment by fedelibre** [comment]
Yes, it occurs every time I close Frescobaldi through X.

I've found a [list of PyQt applications](https://en.wikipedia.org/wiki/PyQt#Notable_applications_that_use_PyQt). I've tested Calibre and Eric: no segfault when I close the applications using X icon. Both use Qt5. Eric uses python3, while Calibre uses python2.

I'll ask to Qt people somewhere and let you know.

**Comment by fedelibre** [comment]
> it looks like the crash happens through an interaction between (Py)Qt and the desktop environment/window manager/graphics server

I'm currently testing on X11.
I get always the segfault when I use gnome-shell (default) or mutter window managers.

If I switch to metacity, then:

- Frescobaldi Fedora package does not segfault
- `python3 src/frescobaldi/frescobaldi --python-ly src/python-ly/` does not segfault either
- this script segfaults:

        #!/usr/bin/env bash
        python3 ~/src/frescobaldi/frescobaldi --python-ly ~/src/python-ly $@
- this script doesn't segfault:

        #!/usr/bin/sh
        exec "/usr/bin/python3" "/home/fede/src/frescobaldi/frescobaldi" "--python-ly" "/home/fede/src/python-ly" "$@"

**Comment by fedelibre** [comment]
> it looks like the crash happens through an interaction between (Py)Qt and the desktop environment/window manager/graphics server

I'm currently testing on X11.
I get always the segfault when I use gnome-shell (default) or mutter window managers.

If I switch to metacity, then:

- Frescobaldi Fedora package does not segfault
- `python3 src/frescobaldi/frescobaldi --python-ly src/python-ly/` does not segfault either
- this script segfaults:

        #!/usr/bin/env bash
        python3 ~/src/frescobaldi/frescobaldi --python-ly ~/src/python-ly $@
- this script doesn't segfault:

        #!/usr/bin/sh
        exec "/usr/bin/python3" "/home/fede/src/frescobaldi/frescobaldi" "--python-ly" "/home/fede/src/python-ly" "$@"

**Comment by fedelibre** [comment]
I've asked on StackOverflow: https://stackoverflow.com/questions/53987363/segfault-when-closing-a-qt5-application-on-certain-window-managers

**Comment by jakob-bebop** [comment]
the same thing is happening here (arch linux, KDE plasma 5.15.3, python 3.7, frescobaldi-3.0.0-3)

**Comment by uliska** [comment]
Is this still happening? If it is in any way related to external packages these might have been updated in the meantime.

**Comment by jakob-bebop** [comment]
I haven't seen it for a long time (almost a year I think)

**Comment by fedelibre** [comment]
I was getting this error 100% of times until few weeks ago.
I've pulled master today - after some weeks - and I confirm that the segfault doesn't occur anymore.

**Comment by uliska** [comment]
Great.
However, I still think this isn't a Freycobaldi bug.

You could test it by checking out a somewhat older state. Maybe before my recent icon-related PR was merged.

And you could test if it is related to themes. I just found out that thr gtk2 theme does *not* crash Frescobaldi anymore on my pc.

**Comment by fedelibre** [comment]
I've tried resetting to a commit of February and I can't reproduce it.
I don't think it's related to theme in my case, as I've always used the system default. Perhaps some change in python or Qt?

**Comment by uliska** [comment]
My assimptipn has always been that this issue is triggered by Qt or PyQt. So for now I'd assume that an update to one of these packages has fixed the underlying issues.

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by fedelibre** [comment]
These are the latest updates containing qt5 on my Fedora 30 (last two September updates are the main suspects):

```
$ rpm -qa --last | grep qt5
python3-pyqt5-sip-4.19.18-5.fc30.x86_64       Fri Sep 20 12:34:46 2019
adwaita-qt5-1.1.0-4.fc30.x86_64               Sun Sep 15 09:18:00 2019
qt5-qtwayland-5.12.4-7.fc30.x86_64            Fri Aug 16 21:31:43 2019
poppler-qt5-devel-0.73.0-14.fc30.x86_64       Fri Aug 16 21:31:32 2019
poppler-qt5-0.73.0-14.fc30.x86_64             Fri Aug 16 21:30:08 2019
qt5-qtbase-devel-5.12.4-4.fc30.x86_64         Fri Aug  2 10:25:11 2019
qt5-qtbase-gui-5.12.4-4.fc30.x86_64           Fri Aug  2 10:25:08 2019
qt5-qtbase-5.12.4-4.fc30.x86_64               Fri Aug  2 10:23:23 2019
qt5-qtbase-common-5.12.4-4.fc30.noarch        Fri Aug  2 10:23:22 2019

```

**Comment by uliska** [comment]
OK, I have *no* idea about what is actually happening here, but I *assume* the issue has somehow vanished due to external circumstances. I close the issue since you can always reopen it or raise a new one if necessary.

**Comment by pedrogmattos** [comment]
I think I'm having the same problem. I don't know most of the jargon you are using, but when I close Frescobaldi with the X I get a python3.7 error, and when I close with Ctrl+Q or File>Exit I do not.
