### ISSUE TITLE
growingtext.py not used

### ISSUE THREAD

**Issue by uliska** [frescobaldi/frescobaldi#1122]
I stumbled over `widgets/growingtext.py` and found no reference whatsoever to this module.

Is this used at all? Is/were there any plans for that?

**Comment by wbsoft** [comment]
I had plans for it, to type multiline text in a small entry. AFAIK it is not used anywhere currently.
Maybe I wanted to use it for a LilyPrompt, where a small lilypond snippet could be entered, and the compiled result displayed direcly below.

**Comment by uliska** [comment]
It *is* not used currently, that's clear. So the question would rather be whether to keep it or not. But since it only "wastes" disk space and doesn't get loaded there's no need to do anything about it. I'll add a comment in the file, though.
