### ISSUE TITLE
Score Wizard music preview seems broken

### ISSUE THREAD

**Issue by uliska** [frescobaldi/frescobaldi#1140]
I'm not sure but at least when I tested just now clicking on Preview in the Score Wizard created the preview dialog, LilyPond ran showing the log, but then no preview was shown.

I *assume* this is related to my changes to the Job code.

**Comment by wbsoft** [comment]
Is this still true? No problems on my system in current master.

**Comment by fedelibre** [comment]
I confirm it's working (on master).

But I can't see anymore the Score Wizard in the File menu. It's available only as a button in the toolbar.

**Comment by fedelibre** [comment]
Ok, it's in File>New from template>Score wizard.
Is this the right location? I would expect only ready made templates in that menu, while the Score Wizard helps *making new templates*. I would move it up in File, right below New from template.

**Comment by wbsoft** [comment]
Urs made the file menu smaller, all the New actions went to a submenu. Indeed an important feature like scorewiz deserves a place in a top-level menu. Closing this as the defect seems to be fixed.

**Comment by uliska** [comment]
I *think* moving it to the submenu is still warranted since the score wizard isn't decidedly more important than, say, "save as...".

However, the naming "from template" isn't good, I suggest "New (advanced)" as consistent with the remainder of the `File` menu.

**Comment by wbsoft** [comment]
I think I agree with that.

As a side note, I'd like to get rid of the "(advanced)" text in the menu actions. Maybe we could rename the regular Save action to "Save Document" (or "Save Current Document"). And then the submenu to simply "Save" instead of "Save (advanced)".
Same with "Close Document" and "New Document".

**Comment by uliska** [comment]
I'll try somethinc and upload a screenshot
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by uliska** [comment]
What about this?

![grafik](https://user-images.githubusercontent.com/1812148/69431639-6ca05d00-0d38-11ea-9214-88096dcc8ea9.png)

I think the leaving it without `...` is more consistent, and the submenu arrow is sufficient.

**Comment by wbsoft** [comment]
I think this look great!
