### ISSUE TITLE
music preview out-of-date when switching from a master .ly file tab to the included .ily file tab

### ISSUE THREAD

**Issue by fedelibre** [frescobaldi/frescobaldi#1144]
Might be related to #867 .
I thought it was reported before but I cannot find any open issue.

I have two files: piece.ily contains only music definitions; piece.ly includes piece.ily and builds the score output. piece.ily contains the `master:` variable which links to piece.ly and allows me to compile the score in the .ily file tab.

Music preview displays correctly while I'm on the piece.ily tab. But if I switch to the piece.ly tab and then back to piece.ily tab, the preview shows only the first two bars of music, even if the piece has now 40 bars. So it seems it's showing some old/cached version of the PDF?

I need to compile again in the piece.ily tab to get the updated PDF preview.
If I then switch to the .ly file and back to .ily, it happens the same.

**Comment by fedelibre** [comment]
I'm trying to reproduce the bug using simple test files but everything works fine. So it might depend on the  input...

**Comment by fedelibre** [comment]
Well, now I cannot reproduce it with the original files! Weird... I didn't change anything except restarting Frescobaldi.

I forgot to give an importnt detail: I'm using a saved session.

**Comment by uliska** [comment]
I'm closing the issue for now. Please reopen it when you can reproduce it.
