### ISSUE TITLE
Separate out Multithreaded job queue

### ISSUE THREAD

**Issue by uliska** [frescobaldi/frescobaldi#1155]
I was asked whether there's a `nogui` option to Frescobaldie to make use of the multithreaded job queue in a command line tool (for use in a headless server).

Of course that's not useful in general, but separating out `python-ly` serves basically the same goal.

So (more as a note to self) I think it might be a good idea to separate out a module for the multithreaded Job Queue ( I think this could retain the PyQt dependencies) to be used independently from Frescobaldi.

@wbsoft do you have a thought on this?

**Comment by uliska** [comment]
@wbsoft is there a chance to `import` frescobaldi to have access to its modules (i.e. job and queue) without actually starting it or its event loop?

**Comment by wbsoft** [comment]
It would be possible to import part of Frescobaldi, but there could be issues. I think is is better to separate out code to a designated headless/server module and have Frescobaldi use it.

**Comment by uliska** [comment]
I now think that it is not really worth the effort. The code is highly integrated in the workings of Frescobaldi now (with both `app` and the whole `job` module), and separating it out would surely be possible but probably not without complications.

I'll drop this wish for now. If someone (most probably myself) will request such  functionality I can still see whether it is easier to do that refactoring - or simply to rebuild the concept in another context.
