### ISSUE TITLE
Icons for dark themes

### ISSUE THREAD

**Issue by uliska** [frescobaldi/frescobaldi#1158]
I've started using Frescobaldi with a dark theme to better match my other desktop settings, to do so I've installed the `adwaita-qt` package for Linux Mint and then chose the "Adwaita Dark" them in Frescobaldi's preferences.

However, this doesn't show proper icons, rendering the UI something close to unusable:

![grafik](https://user-images.githubusercontent.com/1812148/62685885-d5e7a480-b9c3-11e9-8a09-946735198997.png)

![grafik](https://user-images.githubusercontent.com/1812148/62686487-1c89ce80-b9c5-11e9-93af-ef18b85982a1.png)

If I'm not mistaken Frescobaldi *includes* icons from the Tango library and loads them - and there is only one set of icons that simply doesn't match a dark theme.

I'm not really sure what the best way would be to proceed. I think there should be *at least* the option of choosing between two different sets of icons - and we would somehow have to provide them. Or there should be an option to use icons from the given theme - but I don't have any idea how that works yet. And of course there's the fact that we have a number of custom icons provided, which are *not* part of any external theme.

**Comment by uliska** [comment]
The fix in PR #1159 will *not* help with the custom icons provided in Frescobaldi itself. Maybe we should at least provide one dark and one light theme to choose from?

**Comment by Mynamewastakengimmeback** [comment]
uh how did you set it to dark mode?

**Comment by fedelibre** [comment]
You can choose the dark theme in *Edit»Preferences»General Preferences»Style*.
