### ISSUE TITLE
Still (?) error 'could not load the popplerqt5 module', but poppler is installed

### ISSUE THREAD

**Issue by MatthijsG** [frescobaldi/frescobaldi#1174]
Installed Frescobaldi 3 on Linux Mint 19. Get the error that popplerqt5 couldn't be found

> could not load the popplerqt5 module

Installing shows me that the latest version is avalaible.

> $ sudo apt-get install python3-poppler-qt5
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> python3-poppler-qt5 is already the newest version (0.24.2-3build3).
> 0 upgraded, 0 newly installed, 0 to remove and 145 not upgraded.

Is there some kind of binding i should check? Or a workaround to get Frescobaldi 3 to work on Linux?

**Comment by uliska** [comment]
How did you install it, from the Git repo or some releases?
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by MatthijsG** [comment]
> ~$ history | grep "fresco"
>   329  frescobaldi 
>   342  sudo apt-get install frescobaldi 
>   343  frescobaldi 
>   349  history | grep "fresco"

Apparantly straight from the default sources :V 
I will try to re-install it from Git

**Comment by uliska** [comment]
Sorry to hear that.

The guide on the Wiki page is straightforward. And it will allow you to test and enjoy substantial new features.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by MatthijsG** [comment]
No, still no succes after cloning. Not with running directly

> python3 frescobaldi
and with installing it according the wiki 

> sudo python3 setup.py install

**Comment by uliska** [comment]
Hm, I've always found the setup.py approach unreliable. I think https://github.com/frescobaldi/frescobaldi/wiki/Run-Frescobaldi-3-on-Linux doesn't go that way.

**Comment by MatthijsG** [comment]
Are you suggesting to try a different route?

With setup.py still no succes. I get the following error:

> $ python3 setup.py build
> running build
> running build_ext
> building 'popplerqt5' extension
> /usr/bin/sip -I /usr/share/sip -t POPPLER_V0_28_0 -x QTXML_AVAILABLE -c build/temp.linux-x86_64-3.6 -b build/temp.linux-x86_64-3.6/poppler-qt5.sbf -I /usr/share/sip/PyQt5 -n PyQt5.sip -t WS_X11 -t Qt_5_13_0 poppler-qt5.sip
> sip: Usage: sip [-h] [-V] [-a file] [-b file] [-B tag] [-c dir] [-d file] [-D] [-e] [-f] [-g] [-I dir] [-j #] [-k] [-m file] [-o] [-p module] [-P] [-r] [-s suffix] [-t tag] [-w] [-x feature] [-X id:file] [-y file] [-z file] [@file] [file]
> error: command '/usr/bin/sip' failed with exit status 1
> 

Not familiar with sip, it makes no sense to me. And can't find anything helpful in the logs

**Comment by wbsoft** [comment]
Try a newer sip, if possible. It seems that sip does not understand the `-n` option.

**Comment by wbsoft** [comment]
But Frescobaldi should be able to run with the distro-installed popplerqt5 module. Popplerqt5 should be installed using the same Python3 as Frescobaldi.

**Comment by MatthijsG** [comment]
> But Frescobaldi should be able to run with the distro-installed popplerqt5 module. 
I tried different things.
> Popplerqt5 should be installed using the same Python3 as Frescobaldi.
Because i tried different things, i'm afraid there's somewhere a wrong link defined. Logs aren't helpful either :-/ 

So, i will try first a newer sip. 
If that's not working, i go to remove and purge everything from Python and start over.

**Comment by MatthijsG** [comment]
> But Frescobaldi should be able to run with the distro-installed popplerqt5 module. Popplerqt5 should be installed using the same Python3 as Frescobaldi.

This was maybe the error.

Was searching tonight for a different bug (qt and OpenShot). Did not load either. I had to uninstall pyqt5 and sip through pip3 and reinstall it with sudo.
1122  pip3 uninstall pyqt5
1123  pip3 uninstall sip
1124  sudo apt-get install python3-pyqt5 python3-sip
1125  openshot-qt 
After that, also Frescobaldi started again.
