### ISSUE TITLE
dependency on non-namespaced sip

### ISSUE THREAD

**Issue by rdieter** [frescobaldi/frescobaldi#1180]
main.py includes:
import sip
sip.setapi("QString", 2)
sip.setapi("QVariant", 2)

But recent PyQt5 releases use a name-spaced PyQt5.sip module.  I'm not sure the purpose of the aforementioned code lines, so options include removing them or using PyQt5.sip instead.

**Comment by wbsoft** [comment]
these sip.setapi calls can go away.
