### ISSUE TITLE
Does an aborted job send the "finished" signal?

### ISSUE THREAD

**Issue by uliska** [frescobaldi/frescobaldi#1184]
If I call `Job.abort()` it will internally use `_process.kill()` (or `terminate()`). But I'm not sure if the `finished` signal is still sent in that case. https://doc.qt.io/qt-5/qprocess.html is not really clear about this but I have the impression that it rather is *not* emitted.

I want to know that because when aborting a job *queue* I'm aborting all currently running jobs, and I wonder if the aborted jobs show up in the queue's job_finished handler or if I'll do the handling of aborted jobs separately/manually.

**Comment by wbsoft** [comment]
I can test such kind of things, by temporarily inserting print() statements, and see if `finished` gets emitted.

**Comment by uliska** [comment]
Oh my.

I know of print() debugging (of course), *[but very recently I tried out Visual Studio Code as an editor and for the first time got a *working* debugging set-up to run. This is *so* much better because I can inspect everything at runtime and execute the code step by step, monitoring the changes to variables in real time]*

The issue was that I didn't see a clean way (in my current coding mess) to trigger a job abortion.
But in fact that's *totally* simple: just click on the red cross to abort a regular engraving job ;-)

For the record: aborting a job will still trigger the job's `finished` signal.
