### ISSUE TITLE
Document Fonts dialog too large

### ISSUE THREAD

**Issue by wbsoft** [frescobaldi/frescobaldi#1191]
On my little 1024x600 Asus Seashell laptop the new Document Fonts dialog is too large, its height is the main problem, it wants to be at least some 700px high. In the current situation it is difficult to access the button at the bottom of the dialog, as they fall off the screen.
I could not find why it is so high, it might have to do with some hidden widgets.
It would be nice if every dialog in Frescobaldi could at least fit in, say, 960x480 pixels.

**Comment by uliska** [comment]
https://github.com/frescobaldi/frescobaldi/blob/master/frescobaldi_app/fonts/__init__.py#L77

I'll look into it. But I must say that 480 may be pretty small for some things.

**Comment by wbsoft** [comment]
I think I fixed many things, removed double margins and allowed the fontcommand widget to be scrollable. Works fine now on my small laptop :-)

**Comment by wbsoft** [comment]
I think the widgets above the right pane are a bit cluttered. There are three radio buttons, each with an associated widget, to determine which score is displayed in the preview.

Maybe we can simplify that: Only have a combobox, with the url requester next to it (in disabled state). In the combobox are the default examples, then a horizontal line, and then two other entries: Custom... and Current Document.

When the option Custom... is selected, the urlrequester can be enabled.

**Comment by uliska** [comment]
> I think I fixed many things

Thanks, looks all good to me.

> Only have a combobox, with the url requester next to it (in disabled state). In the combobox are the default examples, then a horizontal line, and then two other entries: Custom... and Current Document.

That sounds reasonable.

While we're at it, there's one more UI thing I haven't found a really satisfying solution: I would like to have a UI element displaying all currently selected fonts, regardless which of the left-side tabs is open.

One idea would be to have *two* comboboxes, one for selecting the example (as you suggest) and another one showing the four font names, with checkboxes next to the text fonts indicating whether they are actually used. Of course these entries have to be read-only.

Or do you have another idea? I had thought of labels but everywhere I could think of they would take up too much space or have unwanted layout implications.
