### ISSUE TITLE
AttributeError: 'FileImport' object has no attribute 'isimportable'

### ISSUE THREAD

**Issue by wbsoft** [frescobaldi/frescobaldi#1196]
Reported by user: current master

> Frescobaldi: 3.0.1-git
Extension API: 0.9.0
Python: 3.5.2
Git branch: master
on commit: 6102dde
python-ly: 0.9.5
Qt: 5.5.1
PyQt: 5.5.1
sip: 4.17
poppler: 0.38.0
python-poppler-qt: 0.24.2
OS: Linux-4.15.0-58-generic-x86_64-with-LinuxMint-18.3-sylvia

> Traceback (most recent call last):
File "/home/nyko/frescobaldi/frescobaldi_app/view.py", line 189, in 
dropEvent
self.window().dropEvent(ev)
File "/home/nyko/frescobaldi/frescobaldi_app/mainwindow.py", line 303, 
in dropEvent
if imp.isimportable(url.toLocalFile()):
AttributeError: 'FileImport' object has no attribute `'isimportable'`

> Décrivez ci-dessous ce que vous faisiez (facultatif) :

> Hi,
I get this error then I drop a .ly file.
The method is named "is_importable" in the file_import/__init__.py.
it works by editing the line 302 from mainwindow.py: "if 
imp.is_importable(url.toLocalFile()):"

Note that also imp.openDialog() does not work, e.g. when dropping a MIDI file.

**Comment by uliska** [comment]
I didn't understand the comment about the openDialog() when dropping a MIDI file (dropping where?).
@wbsoft please check if that's fixed too, whatever it is, and comment or close.

**Comment by wbsoft** [comment]
I meant when a midi file is dropped on Frescobaldi from a file manager. Will check this afternoon.

**Comment by uliska** [comment]
Ah, I see. No that didn't work, but should now be fixed too.

**Comment by wbsoft** [comment]
Thanks! I think it works well now. When running an import however (by dropping a MIDI file on the main window), it looks like there is a log drawn over the main window, and the textediting area is not repainted in some cases. But that looks like another issue, maybe caused by the new job structure?

**Comment by uliska** [comment]
Hm, I don't know. I wouldn't rule out that something in the new job code, e.g. some dangling references, are interfering here. But what *happens* after the configuration dialog (and what I see in the code is exactly what I see on my screen) is opening a `job.dialog.Dialog` instance and have it run the import job with `auto_accept` set to `True`.  So after the import (which may be very short) the dialog with the log is closed again.

I don't see any issue with that so you should probably try to come up with a reproducible case. OTOH I'm not sure if the current behaviour is useful at all. It would probably be better to
* run the job silently
* set the waiting cursor
* if the job is successful continue with auto-engraving if requested
* if the job has failed:
    * ensure auto-engraving is turned off
    * open a dialog showing the log, but without automatically closing it

**Comment by wbsoft** [comment]
Thanks for the clarification. On my system the repainting was slow, causing me to think that the log was drawn in the main window, not in dialog. Now I understand that the log dialog is only very shortly visible, and my slow computer caused the display of the log in the main window 😀
