### ISSUE TITLE
Printing simplification proposal

### ISSUE THREAD

**Issue by wbsoft** [frescobaldi/frescobaldi#1198]
Dear friends,

I propose to simplify the printing behaviour of Frescobaldi.

Recently, the Arthur backend of the Poppler library has improved, and it is now usable to print LilyPond scores correctly. (Arthur is the name of the Qt painting system, and the Arthur backend of Poppler paints vector graphics instead of generating very large raster images like the default Splash backend does.)

So I'd like to propose:

- default to using the Arthur backend for printing PDFs in Frescobaldi 3.1, so printing a music PDF is done by Qt and vector-based.
- remove the preference to set a print command and whether or not show a dialog (currently in the helper apps prefs). This pref dates from the days that KDE3 had a `kprinter` command that showed a print dialog for a PDF. If nobody objects I'd be glad to remove that setting.
- only keep a preference "Print PDF directly to CUPS if available". If this is checked and CUPS is available on the system, the PDF is sent directly to the CUPS server.

I think this also improves the printing situation on Mac OS X. After some testing there, we can probably later remove the Mac OS X print warning.

The print resolution preference remains, as it is still used in situations when printing raster-based stuff in a music view (the new upcoming musicview widget can display pdf, svg, and images).

**Comment by wbsoft** [comment]
(Note that if no objections, I do the changes in qpageview-integration first. When all dependencies on qpopplerview are removed and everything works, qpageview-integration will be merged into master)

**Comment by uliska** [comment]
I don't really have an idea what you're talking about - so I have no objections.

But sounds good.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
