### ISSUE TITLE
Lilypond crashes (only) in Frescobaldi

### ISSUE THREAD

**Issue by ccoors** [frescobaldi/frescobaldi#1209]
**Environment:** Arch Linux x86_64, Lilypond 2.19.82
Tested with Frescobaldi 3.0.0 and current Git `master` (9ae33fb4bf487db20a708d0f86c69e9bb0769fb8)

When trying  to engrave my file from Frescobaldi Lilypond crashes
```
Starting lilypond 2.19.82 [DerHoelleRache.ly]...
Processing `/home/ccoors/Music/Lilypond/Mozart/DerHoelleRache.ly'
Parsing...
Interpreting music...ERROR: In procedure ly:trampoline:
ERROR: Wrong type argument in position 3 (expecting Translator): #<freed cell 0x7fd95186ada0; GC missed a reference>
Exited with return code 1.
```

When I run lilypond from a terminal it works fine. Which is strange because I tried it using the exact same command line.
```
$ lilypond -ddelete-intermediate-files -dpoint-and-click --pdf /home/ccoors/Music/Lilypond/Mozart/DerHoelleRache.ly
GNU LilyPond 2.19.82
Processing `/home/ccoors/Music/Lilypond/Mozart/DerHoelleRache.ly'
Parsing...
Interpreting music...[8]
Preprocessing graphical objects...
Interpreting music...
MIDI output to `DerHoelleRache.midi'...
Finding the ideal number of pages...
Fitting music on 2 or 3 pages...
Drawing systems...
Layout output to `/tmp/lilypond-ziHZdQ'...
Converting to `DerHoelleRache.pdf'...
Deleting `/tmp/lilypond-ziHZdQ'...
Success: compilation successfully completed
```

The file I'm trying to build: [DerHoelleRache.zip](https://github.com/frescobaldi/frescobaldi/files/3800795/DerHoelleRache.zip)

Any ideas?

**Comment by uliska** [comment]
I have no idea, but I experienced exactly the same error recently. I didn't try from the command line, but changing things in the input file made it go away.

There are some things beyond the command line that one should investigate: the process's environment and maybe that running a process in QProcess might not be 100% the same aa running in a bash.

One should ask on rhe LilyPond list what that error can indicate and if that condition may be in any way affected by the environment is run in.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by ccoors** [comment]
This is the diff of the env-Vars when run from frescobaldi and my terminal:

```
$ diff fresc.out sys.out 
diff fresc.out sys.out                                                                                                                                                                                                                1 ↵
2a3,4
> WINDOWID=132120583
> COLORTERM=truecolor
8a11
> LANGUAGE=
14a18
> SHELL_SESSION_ID=5b8ddbc149d44526aee03a6df81ec0b4
41a46,48
> KONSOLE_DBUS_SERVICE=:1.1384
> KONSOLE_DBUS_SESSION=/Sessions/1
> PROFILEHOME=
42a50
> KONSOLE_VERSION=190802
48d55
< FRESCOBALDI_SOCKET=frescobaldi-1002-_0#1
51c58
< TERM=linux
---
> TERM=xterm-256color
55a63
> COLORFGBG=15;0
61c69
< SHLVL=3
---
> SHLVL=4
83a92
> KONSOLE_PROFILE_NAME=Profile 1
92a102
> KONSOLE_DBUS_WINDOW=/Windows/1
```

Overriding `TERM` or `FRESCOBALDI_SOCKET` does not change anything (as I would expect). The other things should definitely not be relevant.

Yeah, it occured after I added line 76, if I remove it it works. But it is perfectly valid Lilypond-Syntax. :/

**Comment by uliska** [comment]
I could confirm your error, including the comment with line 76.

It seems this is a LilyPond bug after all (no idea, though why Frescobaldi seems to be related to it). See https://lists.gnu.org/archive/html/lilypond-user/2019-06/msg00134.html

Please update to 2.19.83 and check back. This fixes the problem for me.

**Comment by ccoors** [comment]
It indeed works with 2.19.83. Interesting.

**Comment by uliska** [comment]
I think (but am too lazy) that in hetween something has been fixed in LilyPond.
