### ISSUE TITLE
New QtwebEngine dependency

### ISSUE THREAD

**Issue by uliska** [frescobaldi/frescobaldi#1217]
Implication from #919:

`python3-pyqt5.qtwebengine` has to be listed as a dependency.

I can update the Wiki page, but where else should this go?
And: does that mean `python3-pyqt5.qtwebkit` can be removed from the dependencies list?

**Comment by wbsoft** [comment]
Indeed. The dependencies are listed in INSTALL. I was under the impression that QtWebEngine is part of Qt. When distributors have split/more fine-grained packages they should indeed add QtWebEngine and can remove QtWebKit

**Comment by uliska** [comment]
OK, I'll update

**Comment by wbsoft** [comment]
It's probably a good idea then to list all packages of Qt in INSTALL. A guick
```shell
grep -hr -E 'from PyQt5\.Qt[A-Z]\w+' . | awk '{print $2 }' | cut -d. -f2|sort -u
```
yields
```
QtCore
QtGui
QtNetwork
QtPrintSupport
QtSvg
QtWebChannel
QtWebEngineWidgets
QtWidgets
```
