### ISSUE TITLE
No module named 'PyQt5.QtWebEngineWidgets'

### ISSUE THREAD

**Issue by tank-trax** [frescobaldi/frescobaldi#1225]
**OS: Debian Buster
Problematic package: python3-dbus.mainloop.pyqt5 version 5.11.3+dfsg-1+b3**

I am getting this error 

```
frescobaldi 
Traceback (most recent call last):
  File "/usr/local/bin/frescobaldi", line 4, in <module>
    __import__('pkg_resources').run_script('frescobaldi==3.1', 'frescobaldi')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/frescobaldi-3.1-py3.7.egg/EGG-INFO/scripts/frescobaldi", line 24, in <module>
    import main
  File "/usr/local/lib/python3.7/dist-packages/frescobaldi-3.1-py3.7.egg/frescobaldi_app/main.py", line 34, in <module>
    import app              # Instantiate global signals etc
  File "/usr/local/lib/python3.7/dist-packages/frescobaldi-3.1-py3.7.egg/frescobaldi_app/app.py", line 34, in <module>
    import PyQt5.QtWebEngineWidgets
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
```

I was able to get Frescobaldi running by trying this

`pip3 install PyQt5==5.10.1` but that caused further problems with Cadence which was no longer able to connect to JACKDBUS

**Comment by tank-trax** [comment]
tried reinstalling PyQt5, PyQt5-sip and PyQtWebEngine and now 

`ValueError: PyCapsule_GetPointer called with incorrect name`

Downgrading PyQt5 is not an option as it renders Cadence inoperable.

**Comment by tank-trax** [comment]
tried 

`git checkout py3-qt5`
`python3 frescobaldi`

and it returned...
`TypeError: unhashable type: 'QTextCharFormat'`

**Comment by tank-trax** [comment]
back to master and am getting 
`python3 frescobaldi`

```
frescobaldi/frescobaldi_app/pagedview.py", line 35, in <module>
    import popplerqt5
ValueError: PyCapsule_GetPointer called with incorrect name
```

**Comment by tank-trax** [comment]
resolved installing `python3-pyqt5.qtwebengine`

**Comment by tank-trax** [comment]
would think that `python3-pyqt5.qtwebengine` should be added to the **Depends** list


![fresc deps](https://user-images.githubusercontent.com/41337033/71368719-aacaaf80-2576-11ea-9bc5-b9a716652325.png)

**Comment by uliska** [comment]
It *is* in Frescobaldi's dependencies list. But nog in the distro's package management.

So technically this is not a Frescobaldi issue but we should have an eye on communicating sucv dependency changes.

**Comment by tank-trax** [comment]
I emailed the maintainers at python-apps-team@lists.alioth.debian.org
