### ISSUE TITLE
Frescobaldi 3.1 doesn't detect 64 bit lilypond

### ISSUE THREAD

**Issue by komer83** [frescobaldi/frescobaldi#1230]
First I've installed LilyPond from:
https://www.et.byu.edu/~sorensen/lilypond-devel-2.19.83_2.mpkg

Then installed Frescobaldi 3.1 from this GitHub, but when I'm trying to compile a file I get the 
![Screen Shot 2019-12-28 at 18 13 31](https://user-images.githubusercontent.com/20399230/71546297-21641480-299e-11ea-8cd9-d7b482d3f128.png)

Lilypond is detected by Frescobaldi 
![Screen Shot 2019-12-28 at 18 13 48](https://user-images.githubusercontent.com/20399230/71546303-2e810380-299e-11ea-955b-5fcebd856699.png)

What am I missing?

**Comment by dliessi** [comment]
That package installs the LilyPond binary at `/opt/lilypond/bin/lilypond`.
You need to point Frescobaldi to that location (add it as a new entry in the preferences and make it the default, or edit the existing entry).

The existing entry was probably found by the new version of Frescobaldi in the saved preferences (which persist across versions) and it probably dates back to when your LilyPond.app still worked (pre-Catalina?).

Please reopen the issue if it persists after trying the proposed solution.

**Comment by komer83** [comment]
Thanks, works fine now!
