### ISSUE TITLE
Clear music view

### ISSUE THREAD

**Issue by uliska** [frescobaldi/frescobaldi#1235]
Reuqested by a user:

> I would like a quick way to clear the Music View.

(Especially when something has gone wrong with a compilation)

I could think of an action to clear the music view (and other viewers) that can be added to the viewer's toolbar and context menu.

**Comment by sharonMandel** [comment]
Hi, 
can you please provide more details about your wish? can you attach the image?
thanks

**Comment by wbsoft** [comment]
implemented in 3.1.3 and master
