### ISSUE TITLE
install frecobaldi 3.1 and got run error. 

### ISSUE THREAD

**Issue by yming94** [frescobaldi/frescobaldi#1238]
error message

![image](https://user-images.githubusercontent.com/35079471/71626341-a7f53d80-2bba-11ea-9244-4572c7ad40da.png)

**Comment by TheFoosh** [comment]
Exactly as shown in screenshot above, user "Jones" ... Frescobaldi 3.1 won't run on Windows 10 Home, after update from 3.0, which showed an error upon every launch, but also the splash screen, and ran after the error was dismissed. So far this is a complete dud. I repaired VB 2008 version, reinstalled, but to no avail. It looks like someone, possibly named Jones, hard-coded a path somewhere that should have been left up to the OS to find.

**Comment by KlausBlum** [comment]
Probably the same problem with the hard-coded path: 
Error message on launch when sample extension is started
![Zwischenablage01](https://user-images.githubusercontent.com/25407329/71640301-e4db3600-2c87-11ea-94e0-968956050a5a.png)

**Comment by awrog** [comment]
Same problem here, Frescobaldi.Setup.3.1.exe refuses to start. (Win 10 Pro 1909)
Frescobaldi.Setup.3.0.0-2.exe had no problems.


![error-frescobaldi](https://user-images.githubusercontent.com/12153667/71645654-a53e3980-2cdb-11ea-9e66-088f38f6f492.png)

**Comment by yming94** [comment]
I uninstall (unins000) 3.0.0.2 Then I reinstall (setup) 3.1 and was successful. Freciobaldi runs OK.

**Comment by KlausBlum** [comment]
The problem with the sample extension persists, even with the new installer.  
I cannot judge if it is the same problem or something else...

Open another issue for that?

**Comment by uliska** [comment]
@KlausBlum  Please post yet another screenshot or listing of the complete traceback. So far I'm not sure if it's related to the original issue or if that's an independent issue with the sample extension.

Just to be sure: If you move the sample extension out of the extension directory does Frescobaldi start correctly then?

**Comment by KlausBlum** [comment]
Hi Urs, 
this is the only error message I can offer. After clicking the OK button, nothing happens and Frescobaldi does not launch. 
Yes, if I move the sample extension out of the extension folder, Frescobaldi launches correctly. Also the "boilerplate" extension works correctly (apart from an error message about a character that cannot be read).

**Comment by uliska** [comment]
But with a new installer there should not be that "Jones.000" path there anymore, isn't it?

And could you please retry and post *which* character can't be read in the "boilerplate" extension?

**Comment by KlausBlum** [comment]
Yes, I thought that "Jones.000" path should be gone now. But I don't know what has been fixed for the new installer and what not. 

The unknown character must be one of the typographic quotation marks. I replaced them by simple ones, then it worked. 

![Zwischenablage01](https://user-images.githubusercontent.com/25407329/71646915-7b424280-2cee-11ea-8374-8ee755d28bb7.png)

Does that help?

**Comment by uliska** [comment]
I'm pretty sure that I have not heard of (let alone used) a "charmap" codec. I *think* when you double-click on the text a more complete error traceback should be shown.

**Comment by KlausBlum** [comment]
Sorry, there is nothing more to find. 
When the error message box appears, it is without a detailed description: 

![Zwischenablage01](https://user-images.githubusercontent.com/25407329/71647289-ccedcb80-2cf4-11ea-905a-3c0600085943.png)

Clicking on the arrow left of "invalid metadata" unfolds the description (see above). 
Nothing happens when I click, double-click or right-click on it. 
Double-clicking on the "invalid metadata" line closes the error message box, afterwards Frescobaldi doesn't start. When I close the error message by the OK button, Frescobaldi starts without problems. 
Strange...

**Comment by uliska** [comment]
Ah, that can mean one out of two things (I don't fully recall right now):

* "Invalid metadata" is handled differently from exceptions within an extension
* Double clicking *tries* to open a dialog which crashes due to the codec issue - which now isn't protected anymore by the dialog system.
