### ISSUE TITLE
Frescobaldi 3.1 on Windows 10: no translations available

### ISSUE THREAD

**Issue by KlausBlum** [frescobaldi/frescobaldi#1239]
On Windows 10, there are no languages other than English available. Is there anything I should have done upon installation? 

P.S.: Thanks a million for this great software!  :)

![Zwischenablage01](https://user-images.githubusercontent.com/25407329/71626762-1eac2e00-2bef-11ea-92a4-369567b705e6.png)

**Comment by wbsoft** [comment]
@19joho66 did you build the translation files when preparing the installer?

**Comment by 19joho66** [comment]
Seems like I missed that. I've fixed it and will provide a new setup...

**Comment by wbsoft** [comment]
New setup uploaded. Thanks!
