### ISSUE TITLE
File dialogs don't support hidden files/directories

### ISSUE THREAD

**Issue by uliska** [frescobaldi/frescobaldi#1240]
If it is relevant, this is on Gnome-based Linux desktops (GNOME 3, Cinnamon, didn't test anything else).

The various file dialogs don't support showing hidden files and directories. I realized this when trying to register a LilyPond instance installed in `~/.bin/lilypond`, but it is the case in all file dialogs.

I thought there was an option to switch between Qt and system dialogs, but either that has been dropped or I just don't find it anymore.

In any case it should be possible to select hidden entries in some way.

**Comment by fedelibre** [comment]
I don't have this problem on Fedora 31, GNOME 3.34.2. Ctrl+H allows to toggle the display of hidden files/directories.

![Schermata da 2020-01-02 09-25-40](https://user-images.githubusercontent.com/1644647/71657973-5b3c6e80-2d42-11ea-9780-6339cbe05419.png)

**Comment by uliska** [comment]
Yes, that looks like the desktop's file dialog. I just don't find that option where one could change between Qt and system dialogs.

This is my file dialog (on Cinnamon, but the Gnome laptop is identical), here Ctrl-H doesn't change anything:

![grafik](https://user-images.githubusercontent.com/1812148/71658156-2a106e00-2d43-11ea-9f35-afcf11e1d594.png)

**Comment by fedelibre** [comment]
> I just don't find that option where one could change between Qt and system dialogs.

You should be able to set it running qt5ct in a terminal.

**Comment by uliska** [comment]
Hm, but I *do* recall that there was an option *within* Frescobaldi to do that.

qt5ct gives me the choice between "standard" and "GTK2" on my desktop, which results in this dialog, which *does* provide access to hidden directories but looks inacceptable within the desktop:

![grafik](https://user-images.githubusercontent.com/1812148/71660975-f8040980-2d4c-11ea-8834-e9e557a62004.png)

**Comment by uliska** [comment]
Especially in the context of the beautiful desktop:

![grafik](https://user-images.githubusercontent.com/1812148/71661050-47e2d080-2d4d-11ea-8381-bbe146b45f60.png)

**Comment by fedelibre** [comment]
I've changed the dialog to the same you posted in the first screenshot and I was able to show the hidden files with a **right click on the dialog and click on "Show hidden files"**.

**Comment by uliska** [comment]
Oh!
Thank you, yes that works.
