### ISSUE TITLE
Score wizard not working on Windows 10

### ISSUE THREAD

**Issue by dliessi** [frescobaldi/frescobaldi#1243]
Reported by three users on the LilyPond mailing list:

[1](https://lists.gnu.org/archive/html/lilypond-user/2020-01/msg00008.html):
> The score wizard does nothing for me in Frescobaldi 3.1 (Windows version). I uninstalled it and reinstalled the old version, whose score wizard works fine.

[2](https://lists.gnu.org/archive/html/lilypond-user/2020-01/msg00009.html):
> Correct. Same here. Score Wizard button is completely broken on Windows 10 with version 3.1 - the button just 'clicks' but nothing happens.

[3](https://lists.gnu.org/archive/html/lilypond-user/2020-01/msg00010.html):
> Concur on Score Wizard for 3.1 and latest Win10 (updated 12/16). Toolbar button, menu, and keystrokes all ineffective.

**Comment by uliska** [comment]
Just for the record: No problem on Linux (Debian/GNOME), run from Git.

Is it possible to run Frescobaldi from the command line on Windows? If so, does clicking on the button print anything there?

**Comment by wbsoft** [comment]
@19joho66 maybe you can have a look?

**Comment by 19joho66** [comment]
There was a folder missing in the installation. I've fixed that in the Setup 3.1.1

**Comment by wbsoft** [comment]
Thank you Jorg!
