### ISSUE TITLE
Error when opening Frescobaldi 3.1.1

### ISSUE THREAD

**Issue by greenjaed** [frescobaldi/frescobaldi#1253]
This is on Windows 10
I recently intalled Frescobaldi 3.1.1 and tried to run it, but ran into the attached error:

![frescobaldi python error](https://user-images.githubusercontent.com/5624793/72687474-f65b7500-3ab2-11ea-842a-44d23b6c62ee.png)

**Comment by uliska** [comment]
See yesterday's #1252  and please report back if we can close this again.

**Comment by greenjaed** [comment]
Yeah, I just did this.  Issue resolved.
