### ISSUE TITLE
Add (emphatic) instruction to Downloads page: uninstall prior versions first (Windows)

### ISSUE THREAD

**Issue by JoanEliot** [frescobaldi/frescobaldi#1259]
#1252 is closed but the problem isn't fixed yet, so: 
Please add a remark in the Download page's Windows section, ideally in bold type or otherwise emphasized, that previous versions must be uninstalled or the new install won't work. I'd vote for reopening the issue until it's fixed would as well, but a simple can't-miss-it instruction for downloaders would be adequate. 

Thank you.

**Comment by 19joho66** [comment]
I will also work on an uninstaller as soon as possible...

**Comment by wbsoft** [comment]
Website has the remark. It would be nice if the installer could handle this automatically 🙂
