### ISSUE TITLE
re-docking panels is broken in Wayland

### ISSUE THREAD

**Issue by fedelibre** [frescobaldi/frescobaldi#1273]
This happens on GNOME on Wayland, Fedora 31.
When I undock a tool, I'm not able to re-dock it anywhere. It becomes an independent window and there's no button or menu to re-dock it. The dock/undock button is visible when the panel is docked, but it disappears after I've detached a tool from the main window. Dragging the panel doesn't work either.

This is very annoying, because if you close the tool and open it again it will appear in the last state (independent window). Apparently, you have to manually fix the frescobaldi.conf file or (better) launching Frescobaldi on X11, where the dock button is still visible:

    QT_QPA_PLATFORM=xcb frescobaldi

**Comment by fedelibre** [comment]
Perhaps #1261 is related?

**Comment by fedelibre** [comment]
> Judging from https://bugreports.qt.io/browse/QTBUG-87332, maybe this is to be fixed on the Qt side?

I've just received an email notification saying that this bugs has been fixed. Here's the code review:
https://codereview.qt-project.org/c/qt/qtbase/+/470671

A related issue has been added which affects also Qt6. I hope they will backport the fix in Qt5.
Menawhile I might try applying the patch in a flatpak build.. I don't know if it will work with the Qt 5.x.y branch.
This in my next week TODO list.

**Comment by fedelibre** [comment]
For the records, here's the commit:
https://code.qt.io/cgit/qt/qtbase.git/commit/?id=581c4bcb62a9d3cbb4c33df3f0f7a0a965225e74

I've tried applying this patch to the 5.15 branch of qtbase, but it doesn't work:

```
$ git am qtbase-docks-wayland.patch
Applying: Use platform drags for drags of docks and toolbars on wayland
error: patch failed: src/widgets/widgets/qdockwidget.cpp:253
error: src/widgets/widgets/qdockwidget.cpp: patch does not apply
error: patch failed: src/widgets/widgets/qmainwindowlayout_p.h:571
error: src/widgets/widgets/qmainwindowlayout_p.h: patch does not apply
error: patch failed: src/widgets/widgets/qtoolbar.cpp:293
error: src/widgets/widgets/qtoolbar.cpp: patch does not apply
Patch failed at 0001 Use platform drags for drags of docks and toolbars on wayland
```

I've asked on above issue if they intend to backport this patch to 5.15 branch.

**Comment by fedelibre** [comment]
I confirm that this bug is fixed in Qt 6.7. I'm using Frescobaldi flatpak built using Frescobaldi qt6 branch of #1780

**Comment by fedelibre** [comment]
Fixed by #1780

**Comment by jeanas** [comment]
It does print

```
This plugin supports grabbing the mouse only for popup windows
```

Probably harmless?

**Comment by fedelibre** [comment]
When you click on the dock/undock icons, nothing is printed.

I see the same message only when I _drag_ a panel from one place to another.
It seems harmless.
