### ISSUE TITLE
missing desktop file

### ISSUE THREAD

**Issue by wbsoft** [frescobaldi/frescobaldi#1282]
recent master:
error: can't copy 'linux/org.frescobaldi.Frescobaldi.desktop': doesn't exist or not a regular file

in the linux/ folder, that file is not there.

**Comment by fedelibre** [comment]
It must be generated from the template file called `org.frescobaldi.Frescobaldi.desktop.in` so that it includes the translations from the po files, using Make:

    make -C linux

It's documented [here](https://github.com/frescobaldi/frescobaldi/blob/master/INSTALL#L36).

**Comment by wbsoft** [comment]
thanks!
