### ISSUE TITLE
Frescobaldi won't launch in Windows

### ISSUE THREAD

**Issue by DeTommie** [frescobaldi/frescobaldi#1288]
Frescobaldi won't launch in Windows with the following message:
![Frescobaldi](https://user-images.githubusercontent.com/11413460/79849556-ea899280-83c2-11ea-92a0-525e73700461.png)

**Comment by 19joho66** [comment]
Did the uninstaller run when you used the new setup?
The error you describe occurs when the prevoious Frescobaldi version has not been uninstalled completely.
Normally this is done by the setup but maybe something went wrong with your installation.

**Comment by DeTommie** [comment]
The uninstaller worked fine. I ran it again just to be sure.
FYI: the user Jones.000 is not a user on my computer.

**Comment by 19joho66** [comment]
User Jones.000 is the user name (mine) under which cx_freeze was run for building the setup. 
Your error looks like some qt dll files could not be found. Did you (already try to) install as administrator?

**Comment by DeTommie** [comment]
The uninstaller didn't remove the folder completely. I uninstalled, removed the Frescobaldi folder and installed ad Admin. Now it works.
