### ISSUE TITLE
[Wayland] Cannot paste from other applications

### ISSUE THREAD

**Issue by fedelibre** [frescobaldi/frescobaldi#1293]
Probably related to #1248 and #1258 

This problem appeared after upgrading Fedora from 31 to 32, so I guess that a new version of Wayland (currently 1.18.0) might explain this new problem: if I copy some text in a terminal or a browser, can't paste it in Frescobaldi (or last text copied *within Frescobaldi* will be pasted).

As usual, the workaround is launching Frescobaldi this way:

    QT_QPA_PLATFORM=xcb frescobaldi

**Comment by uliska** [comment]
What happens when you try to paste that copied text into something else?

From your description it may seem like the problem might not be the *pasting* in Frescobaldi but failing to *copy* from the terminal in the first place.

**Comment by fedelibre** [comment]
No, I'm pretty sure.
The text is copied and can be pasted in any other application except Frescobaldi.

**Comment by fedelibre** [comment]
No, I cannot reproduce it anymore. Let's close it.
