### ISSUE TITLE
AttributeError: 'PreviewJob' object has no attribute 'lilypond_version' 

### ISSUE THREAD

**Issue by wbsoft** [frescobaldi/frescobaldi#1307]
A user reported the following error:

>  File "/home/k/Frescobaldi 3.1.2/frescobaldi-frescobaldi-2560bee/frescobaldi_app/job/lilypond.py", 
> line 153, in backend_args
> if self.embed_source_code and self.lilypond_version >= (2, 19, 39): 
> AttributeError: 'PreviewJob' object has no attribute 'lilypond_version' 

Is seems to be in the new job code.

**Comment by uliska** [comment]
I'll try to find the time to look into this. After I'll have found the time to update Frescobaldi to the newly factored-out modules...

**Comment by uliska** [comment]
Reported:

> If you received a previous post about success, I was mistaken. I execute the wrong code.
>
> Making the suggested modification to lilypond.py changes the error to

```python
TypeError: '>=' not supported between instances of 'CachedProperty' and 'tuple'
```
