### ISSUE TITLE
Request: session main file

### ISSUE THREAD

**Issue by esseci77** [frescobaldi/frescobaldi#1338]
Frescobaldi is a fondamental tool for writing music with lilypond, thank you for writing it.
I would to share some of my user experience as a composer:  I usually work with a lot of files 
because my approach is to use a separate file for every instrument and this means a lot of tabs opened in the 
Frescobaldi workspace; every time, after editing and so on, I want to compile the score, I have to search for the
main file to compile in dozens of tabs...if I compile with the focus on the wrong tab - by my mistake, of course - 
I got errors  on my log and garbage on my working directory because in my source tree only one file is intended to be 
compiled, and I have to spend some time to figure out what's happened because I'm concentrated on the music
I'm writing, not on the compiling process...

I think that it would be very useful the capability to set a "main file" for every session, so every time the "compile" button 
is pressed,  this "main file" - if set - is automatically processed, and not the current tab.

Thank you in advance for your attention,

Simone Campanini

PS: I usually wrote every piece with frescobaldi/lilypond since about fifteen years. And for me it's really a pain when a 
publisher ask me to translate the score to finale or sibelius because this is the "standard"....

**Comment by uliska** [comment]
This hs been a Frescobaldi feature for ages (if not from the beginnig, but I don't know).

You can either look up "mster variables" in thge manual or use the "always compile" check box in the "LilyPond" menu or any of the tabs' context menu.

**Comment by esseci77** [comment]
Found "Engrave this file" in the tabs context menu. Never seen it before...
Thank you so much!!

**Comment by wbsoft** [comment]
Ok, while I think it is desirable to have some more support for hierarchical file ordering/dependencies in open documents, I can close this one I think, because the "master" variable and the "Always engrave this document" features. Thanks for your nice words!
I
