### ISSUE TITLE
Error: does not work on Big Sur

### ISSUE THREAD

**Issue by siciarek** [frescobaldi/frescobaldi#1339]
Application does not open the window. It starts, icon shows on the Taskbar, menu bar updates too, application utilizes 100% of CPU and after a few seconds (~10) on Activity Monitor is visible as invalid.

![image](https://user-images.githubusercontent.com/27905/99143801-b593a480-2660-11eb-829b-7401c514cfa3.png)

**Comment by dliessi** [comment]
Duplicate of #1336
