### ISSUE TITLE
v3.1.3 pre release?

### ISSUE THREAD

**Issue by iilei** [frescobaldi/frescobaldi#1340]
Hi, I have high hopes for the upcoming version that includes the fix for [this error concerning PreviewJob](https://github.com/frescobaldi/frescobaldi/issues/1307).

Would you mind to publish a pre-release based on branch v3.1.x to I can beta-test it on Mac OS?

**Comment by fedelibre** [comment]
Those two commits were added to the 3.1.3 release, see [this list](https://github.com/frescobaldi/frescobaldi/compare/v3.1.2...v3.1.3).

Mac OS package  is not ready yet,  but should be available soon.

**Comment by iilei** [comment]
thank you!
