### ISSUE TITLE
Wish : Add the possibility for the user to choose line endings style

### ISSUE THREAD

**Issue by Yanncha** [frescobaldi/frescobaldi#1359]
Hello !

I didn't find a setting in Frescobaldi (3.1.3) to choose default line endings style to use.

I work on Linux with a versioning system (mercurial), and all my files have LF line endings, which is fine and kept also in the versioned repositories.

However, when someone wants to collaborate and runs Frescobaldi on Windows, all line endings get converted to Windows style in the modified files, and this gets versioned with the line endings changed on all lines. So right now in these case we have to open the file in another editor (e.g. Notepad++ or Kate) to convert the line endings to Linux style before committing.

I think there may be as well options in mercurial to handle it automatically, but it may be cleaner if done natively by the editor. What do you think ?

Yann

**Comment by fedelibre** [comment]
Hi @Yanncha 

You asked the same question almost 4 years ago :-)
Unfortunately nobody worked on it yet.

Closing in favour of #982

**Comment by Yanncha** [comment]
Hi @fedelibre !

Oh, sorry ! I searched the repo for similar questions but didn't find. And I forgot to check if I opened issues !!
Completely forgot about this one :) Thanks for pointing out !
