### ISSUE TITLE
Cannot "redock" views (windows)

### ISSUE THREAD

**Issue by kledeen** [frescobaldi/frescobaldi#1361]
On MacOS - Big Sur, Frescobaldi 3.1.2  If a Music View, or SVG view is undocked there is no way (that I have found) to redock it.  Closing and restarting did not restore docking.

**Comment by fedelibre** [comment]
You should see a dock/undock icon on the top right of the panel:

![fresco-dock-undock](https://user-images.githubusercontent.com/1644647/110312336-4114b500-8005-11eb-926e-86303e7e5f2f.png)

If you don't see it, it's a bug.

**Comment by kledeen** [comment]
I don't see it.  Screenshot attached.  I cannot do SVG view because of a
known defect, Issue #1244.

Image below show both windows (entry and music view).

[image: Screen Shot 2021-03-08 at 9.43.19 AM.png]


Ken Ledeen

Mobile:                617-817-3183
www.nevo.com
www.bitsbook.com
tiny.cc/KenLedeen
tiny.cc/KenLedeenAmazon

ᐧ

**Comment by kledeen** [comment]
Downloaded and installed 3.1.3.  Problem is resolved in this release.  Redocking behaves as expected (drag undocked window, etc.)
