### ISSUE TITLE
Frescobaldi on Mac OSX 10.13.6 (High Sierra) does not compile PDF-File

### ISSUE THREAD

**Issue by fg14542** [frescobaldi/frescobaldi#1364]
I installed Frescobaldi via homebrew, unfortunately the compilation-process creates only a midi-File, bot no PDF. I have no idea which screw to turn, can you please help me:

Frescobaldi: 3.1.3
Extension API: 0.9.0
Python: 3.9.1
python-ly: 0.9.7
Qt: 5.11.3
PyQt: 5.15.2
sip: 4.19.24
poppler: 20.12.1
python-poppler-qt: 0.75.0
OS: macOS-10.13.6-x86_64-i386-64bit
installation kind: standalone .app bundle

**Comment by fedelibre** [comment]
Can you please paste a minimal example you're trying to compile and the lilypond logs?

**Comment by fg14542** [comment]
In the meantime I got it running by uncommenting the '\midi {} ' - line in the lilypond-source file. But it seems that you can either compile to a pdf-file or to a midi-file. In a previous installation both output-files were compiled at the same time. I am not sure if this is the right place to ask this question.

**Comment by fedelibre** [comment]
Hard to say without seeing the input file you're compiling... but I guess there's an error in your input file.

This creates only a PDF file:

```
\version "2.22.0"
\score {
  { c }
}
```

This creates only a MIDI file:

```
\version "2.22.0"
\score {
  { c }
  \midi{}
}
```

This creates a MIDI and a PDF file:

```
\version "2.22.0"
\score {
  { c }
  \layout{}
  \midi{}
}
```
