### ISSUE TITLE
gs fails to run within Frescobaldi, plain Lyilypond works ok (Windows)

### ISSUE THREAD

**Issue by VladimirSlavik** [frescobaldi/frescobaldi#1369]
Frescobaldi 3.1.3, Lilypond 2.22.0. I can't compile anything and get only errors like this: ```warning: `(gs -q -dNODISPLAY -dNOSAFER -dNOPAUSE -dBATCH -dAutoRotatePages=/None -dPrinted=false ./tmp--tmp-8501569)' failed (1)```

I have also 2.16.1 and 2.18.2, which both work in Frescobaldi (do not have this problem). All of these versions are installed from official installers linked from lilypond.org. Automatic version selection is turned off and 22 is the default. Path to lilypond is set, too, but does not seem to have any effect. (Screenshot of all the settings attached below.)

If I run lilypond directly as ```C:\Users\Vladimir\Music\komunitni-noty\hymnus_sv_krize>"C:\Program Files\LilyPond\2.18.2\usr\bin\lilypond.exe" "hymnus svatého kříže.ly"```, it just works OK. Swapping `lilypond-windows.exe` for `lilypond.exe` in Frescobaldi settings does not change the error.

I'm on Windows 7 with all the updates. The system is heavily customized, but there's nothing in `%path%` related to Lilypond or gs. I've also checked the web for previous instances of this error message and I'm almost sure it's not the font - this happens for all files, not just these with `\sans` or guitar chords.

I'm not exactly happy to go removing the bits that actually work in favor of testing the bits that don't, so I have not tried that. I tried renaming the directories with all other versions, but that did not change anything either.

So I think the only explanation left is that it's a Frescobaldi problem, unfortunately. That's a pity, because I like it a lot... Thank you for it anyway!

![frescobaldi-fail](https://user-images.githubusercontent.com/15903878/115363009-5ebb6980-a1c2-11eb-8b18-fcabab86b0b6.png)

**Comment by rpspringuel** [comment]
Perhaps a Windows version of #1356.

**Comment by vitkolos** [comment]
I had a similar problem but then I realized that I had the PDF file opened in Adobe Acrobat which had blocked the `gs` from modifying it. Closing the Adobe Acrobat helped.

This is not a solution to your issue, just a note to my future self in case I ever end up here again.

**Comment by fedelibre** [comment]
> I had a similar problem but then I realized that I had the PDF file opened in Adobe Acrobat which had blocked the `gs` from modifying it. Closing the Adobe Acrobat helped.

Yes, I think this is a Windows issue. I'm closing the issue.
