### ISSUE TITLE
ERROR: In procedure ly:trampoline

### ISSUE THREAD

**Issue by jehojakim** [frescobaldi/frescobaldi#1372]
If I try to compile the snippet below from within Frecobaldi, I get the error

ERROR: In procedure ly:trampoline:
ERROR: Wrong type argument in position 3 (expecting Translator): #<freed cell 0x7f69e96ad5f0; GC missed a reference>
Afgesloten met returncode 1.

If I compile the same cod with lilypond from the command line, no problem.

The error arises when adding the lyrics, more specifically, after adding a character after the line "Saul, Saul, Saul, Saul, was ver -- folgst "; in the case below, a ´d´. It makes no difference if I add it in bass I or bass II in this snippet.

 `\version "2.19.82"

\header {
  title = "Saul, Saul, was verfolchst du mich"
  composer = "Heinrich Schütz (1585-1672)"
  opus = "SWV 415"
}

\paper {
  #(set-paper-size "a3landscape")
}

global = {
  \key c \major
  \numericTimeSignature
  \time 3/2
  \tempo 4=100
}

scoreAViolinI = \relative c'' {
  \global
R1.*12

}

scoreAViolinII = \relative c'' {
  \global
R1.*12

}

scoreASopranoOne = \relative c'' {
  \global
R1.*8

}

scoreASopranoTwo = \relative c'' {
  \global
R1.*8

}

scoreAAltoChoirI = \relative c' {
  \global
R1.*4

}

scoreATenorChoirI = \relative c' {
  \global
R1.*4

}

scoreABassOne = \relative c {
  \global
r2 a, r
d r f
a1.
d,4 d d2. c4
c1 r2
R1.*4

}

scoreABassTwo = \relative c {
  \global
r2 d, r
a' r d
f1 d2
d d2. cis4
d1 r2
R1.*4
}

scoreASopranoOneVerse = \lyricmode {

}

scoreASopranoTwoVerse = \lyricmode {

}

scoreAAltoVerseChoirI = \lyricmode {

}

scoreATenorVerseChoirI = \lyricmode {

}

scoreABassOneVerse = \lyricmode {
Saul, Saul, Saul, Saul, was ver -- folgst d

}

scoreABassTwoVerse = \lyricmode {
Saul, Saul, Saul, Saul, was ver -- folgst 

}

scoreARehearsalMidiChoirI = #
(define-music-function
 (parser location name midiInstrument lyrics) (string? string? ly:music?)
 #{
   \unfoldRepeats <<
     \new Staff = "soprano1" \new Voice = "soprano1" { \scoreASopranoOne }
     \new Staff = "soprano2" \new Voice = "soprano2" { \scoreASopranoTwo }
     \new Staff = "alto" \new Voice = "alto" { \scoreAAltoChoirI }
     \new Staff = "tenor" \new Voice = "tenor" { \scoreATenorChoirI }
     \new Staff = "bass1" \new Voice = "bass1" { \scoreABassOne }
     \new Staff = "bass2" \new Voice = "bass2" { \scoreABassTwo }
     \context Staff = $name {
       \set Score.midiMinimumVolume = #0.5
       \set Score.midiMaximumVolume = #0.5
       \set Score.tempoWholesPerMinute = #(ly:make-moment 100 4)
       \set Staff.midiMinimumVolume = #0.8
       \set Staff.midiMaximumVolume = #1.0
       \set Staff.midiInstrument = $midiInstrument
     }
     \new Lyrics \with {
       alignBelowContext = $name
     } \lyricsto $name $lyrics
   >>
 #})

scoreASopranoChoirII = \relative c'' {
  \global
R1.*16

}

scoreAAltoChoirII = \relative c' {
  \global
R1.*16 % Muziek volgt hier.

}

scoreATenorChoirII = \relative c' {
  \global
R1.*16  % Muziek volgt hier.

}

scoreABassChoirII = \relative c {
  \global
R1.*16  % Muziek volgt hier.

}

scoreASopranoVerseChoirII = \lyricmode {
  % Liedtekst volgt hier.

}

scoreAAltoVerseChoirII = \lyricmode {
  % Liedtekst volgt hier.

}

scoreATenorVerseChoirII = \lyricmode {
  % Liedtekst volgt hier.

}

scoreABassVerseChoirII = \lyricmode {
  % Liedtekst volgt hier.

}

scoreARehearsalMidiChoirII = #
(define-music-function
 (parser location name midiInstrument lyrics) (string? string? ly:music?)
 #{
   \unfoldRepeats <<
     \new Staff = "soprano" \new Voice = "soprano" { \scoreASopranoChoirII }
     \new Staff = "alto" \new Voice = "alto" { \scoreAAltoChoirII }
     \new Staff = "tenor" \new Voice = "tenor" { \scoreATenorChoirII }
     \new Staff = "bass" \new Voice = "bass" { \scoreABassChoirII }
     \context Staff = $name {
       \set Score.midiMinimumVolume = #0.5
       \set Score.midiMaximumVolume = #0.5
       \set Score.tempoWholesPerMinute = #(ly:make-moment 100 4)
       \set Staff.midiMinimumVolume = #0.8
       \set Staff.midiMaximumVolume = #1.0
       \set Staff.midiInstrument = $midiInstrument
     }
     \new Lyrics \with {
       alignBelowContext = $name
     } \lyricsto $name $lyrics
   >>
 #})

scoreASopranoChoirIII = \relative c'' {
  \global
R1.*16  % Muziek volgt hier.

}

scoreAAltoChoirIII = \relative c' {
  \global
R1.*16  % Muziek volgt hier.

}

scoreATenorChoirIII = \relative c' {
  \global
R1.*16  % Muziek volgt hier.

}

scoreABassChoirIII = \relative c {
  \global
R1.*16  % Muziek volgt hier.

}

scoreASopranoVerseChoirIII = \lyricmode {
  % Liedtekst volgt hier.

}

scoreAAltoVerseChoirIII = \lyricmode {
  % Liedtekst volgt hier.

}

scoreATenorVerseChoirIII = \lyricmode {
  % Liedtekst volgt hier.

}

scoreABassVerseChoirIII = \lyricmode {
  % Liedtekst volgt hier.

}

scoreARehearsalMidiChoirIII = #
(define-music-function
 (parser location name midiInstrument lyrics) (string? string? ly:music?)
 #{
   \unfoldRepeats <<
     \new Staff = "soprano" \new Voice = "soprano" { \scoreASopranoChoirIII }
     \new Staff = "alto" \new Voice = "alto" { \scoreAAltoChoirIII }
     \new Staff = "tenor" \new Voice = "tenor" { \scoreATenorChoirIII }
     \new Staff = "bass" \new Voice = "bass" { \scoreABassChoirIII }
     \context Staff = $name {
       \set Score.midiMinimumVolume = #0.5
       \set Score.midiMaximumVolume = #0.5
       \set Score.tempoWholesPerMinute = #(ly:make-moment 100 4)
       \set Staff.midiMinimumVolume = #0.8
       \set Staff.midiMaximumVolume = #1.0
       \set Staff.midiInstrument = $midiInstrument
     }
     \new Lyrics \with {
       alignBelowContext = $name
     } \lyricsto $name $lyrics
   >>
 #})

scoreAContrabass = \relative c {
  \global
d,1.
d1 d2
d1 g2~
g f1

}

scoreAViolinIPart = \new Staff \with {
  instrumentName = "Viool I"
  shortInstrumentName = "Vl. I"
  midiInstrument = "violin"
} \scoreAViolinI

scoreAViolinIIPart = \new Staff \with {
  instrumentName = "Viool II"
  shortInstrumentName = "Vl. II"
  midiInstrument = "violin"
} \scoreAViolinII

scoreAChoirIPart = \new ChoirStaff \with {
  \consists "Instrument_name_engraver"
  instrumentName = "Koor I"
  shortInstrumentName = "K. I"
} <<
  \new Staff \with {
    midiInstrument = "choir aahs"
    instrumentName = "Sopraan I"
    shortInstrumentName = "S. I"
  } { \scoreASopranoOne }
  \addlyrics { \scoreASopranoOneVerse }
  \new Staff \with {
    midiInstrument = "choir aahs"
    instrumentName = "Sopraan II"
    shortInstrumentName = "S. II"
  } { \scoreASopranoTwo }
  \addlyrics { \scoreASopranoTwoVerse }
  \new Staff \with {
    midiInstrument = "choir aahs"
    instrumentName = "Alt"
    shortInstrumentName = "A."
  } { \scoreAAltoChoirI }
  \addlyrics { \scoreAAltoVerseChoirI }
  \new Staff \with {
    midiInstrument = "choir aahs"
    instrumentName = "Tenor"
    shortInstrumentName = "T."
  } { \clef "treble_8" \scoreATenorChoirI }
  \addlyrics { \scoreATenorVerseChoirI }
  \new Staff \with {
    midiInstrument = "choir aahs"
    instrumentName = "Bas I"
    shortInstrumentName = "B. I"
  } { \clef bass \scoreABassOne }
  \addlyrics { \scoreABassOneVerse }
  \new Staff \with {
    midiInstrument = "choir aahs"
    instrumentName = "Bas II"
    shortInstrumentName = "B. II"
  } { \clef bass \scoreABassTwo }
  \addlyrics { \scoreABassTwoVerse }
>>

scoreAChoirIIPart = \new ChoirStaff \with {
  \consists "Instrument_name_engraver"
  instrumentName = "Koor II"
  shortInstrumentName = "K. II"
} <<
  \new Staff \with {
    midiInstrument = "choir aahs"
    instrumentName = "Sopraan"
    shortInstrumentName = "S."
  } { \scoreASopranoChoirII }
  \addlyrics { \scoreASopranoVerseChoirII }
  \new Staff \with {
    midiInstrument = "choir aahs"
    instrumentName = "Alt"
    shortInstrumentName = "A."
  } { \scoreAAltoChoirII }
  \addlyrics { \scoreAAltoVerseChoirII }
  \new Staff \with {
    midiInstrument = "choir aahs"
    instrumentName = "Tenor"
    shortInstrumentName = "T."
  } { \clef "treble_8" \scoreATenorChoirII }
  \addlyrics { \scoreATenorVerseChoirII }
  \new Staff \with {
    midiInstrument = "choir aahs"
    instrumentName = "Bas"
    shortInstrumentName = "B."
  } { \clef bass \scoreABassChoirII }
  \addlyrics { \scoreABassVerseChoirII }
>>

scoreAChoirIIIPart = \new ChoirStaff \with {
  \consists "Instrument_name_engraver"
  instrumentName = "Koor III"
  shortInstrumentName = "K. III"
} <<
  \new Staff \with {
    midiInstrument = "choir aahs"
    instrumentName = "Sopraan"
    shortInstrumentName = "S."
  } { \scoreASopranoChoirIII }
  \addlyrics { \scoreASopranoVerseChoirIII }
  \new Staff \with {
    midiInstrument = "choir aahs"
    instrumentName = "Alt"
    shortInstrumentName = "A."
  } { \scoreAAltoChoirIII }
  \addlyrics { \scoreAAltoVerseChoirIII }
  \new Staff \with {
    midiInstrument = "choir aahs"
    instrumentName = "Tenor"
    shortInstrumentName = "T."
  } { \clef "treble_8" \scoreATenorChoirIII }
  \addlyrics { \scoreATenorVerseChoirIII }
  \new Staff \with {
    midiInstrument = "choir aahs"
    instrumentName = "Bas"
    shortInstrumentName = "B."
  } { \clef bass \scoreABassChoirIII }
  \addlyrics { \scoreABassVerseChoirIII }
>>

scoreAContrabassPart = \new Staff \with {
  instrumentName = "Contrabas"
  shortInstrumentName = "Cb."
  midiInstrument = "contrabass"
} { \clef bass \scoreAContrabass }

\score {
  <<
    \scoreAViolinIPart
    \scoreAViolinIIPart
    \scoreAChoirIPart
    \scoreAChoirIIPart
    \scoreAChoirIIIPart
    \scoreAContrabassPart
  >>
  \layout { }
  \midi { }
}

% MIDI-oefenbestanden:
\book {
  \bookOutputSuffix "choir1-soprano1"
  \score {
    \scoreARehearsalMidiChoirI "soprano1" "soprano sax" \scoreASopranoOneVerse
    \midi { }
  }
}

\book {
  \bookOutputSuffix "choir1-soprano2"
  \score {
    \scoreARehearsalMidiChoirI "soprano2" "soprano sax" \scoreASopranoTwoVerse
    \midi { }
  }
}

\book {
  \bookOutputSuffix "choir1-alto"
  \score {
    \scoreARehearsalMidiChoirI "alto" "soprano sax" \scoreAAltoVerseChoirI
    \midi { }
  }
}

\book {
  \bookOutputSuffix "choir1-tenor"
  \score {
    \scoreARehearsalMidiChoirI "tenor" "tenor sax" \scoreATenorVerseChoirI
    \midi { }
  }
}

\book {
  \bookOutputSuffix "choir1-bass1"
  \score {
    \scoreARehearsalMidiChoirI "bass1" "tenor sax" \scoreABassOneVerse
    \midi { }
  }
}

\book {
  \bookOutputSuffix "choir1-bass2"
  \score {
    \scoreARehearsalMidiChoirI "bass2" "tenor sax" \scoreABassTwoVerse
    \midi { }
  }
}

% MIDI-oefenbestanden:
\book {
  \bookOutputSuffix "choir2-soprano"
  \score {
    \scoreARehearsalMidiChoirII "soprano" "soprano sax" \scoreASopranoVerseChoirII
    \midi { }
  }
}

\book {
  \bookOutputSuffix "choir2-alto"
  \score {
    \scoreARehearsalMidiChoirII "alto" "soprano sax" \scoreAAltoVerseChoirII
    \midi { }
  }
}

\book {
  \bookOutputSuffix "choir2-tenor"
  \score {
    \scoreARehearsalMidiChoirII "tenor" "tenor sax" \scoreATenorVerseChoirII
    \midi { }
  }
}

\book {
  \bookOutputSuffix "choir2-bass"
  \score {
    \scoreARehearsalMidiChoirII "bass" "tenor sax" \scoreABassVerseChoirII
    \midi { }
  }
}

% MIDI-oefenbestanden:
\book {
  \bookOutputSuffix "choir3-soprano"
  \score {
    \scoreARehearsalMidiChoirIII "soprano" "soprano sax" \scoreASopranoVerseChoirIII
    \midi { }
  }
}

\book {
  \bookOutputSuffix "choir3-alto"
  \score {
    \scoreARehearsalMidiChoirIII "alto" "soprano sax" \scoreAAltoVerseChoirIII
    \midi { }
  }
}

\book {
  \bookOutputSuffix "choir3-tenor"
  \score {
    \scoreARehearsalMidiChoirIII "tenor" "tenor sax" \scoreATenorVerseChoirIII
    \midi { }
  }
}

\book {
  \bookOutputSuffix "choir3-bass"
  \score {
    \scoreARehearsalMidiChoirIII "bass" "tenor sax" \scoreABassVerseChoirIII
    \midi { }
  }
}

`

**Comment by Jean-Abou-Samra** [comment]
@jehojakim This is a known LilyPond issue that was fixed in recent development versions. The problem was occurring sporadically with unrelated circumstances (such as running from Frescobaldi or not in your case). You should upgrade to [LilyPond 2.23.2](lilypond.org/development.html).
