### ISSUE TITLE
"Point and Click" feature not working (Win10, frescobaldi 3.1.3, and "multibyte filename")

### ISSUE THREAD

**Issue by t-kitagishi** [frescobaldi/frescobaldi#1376]
After upgrading frescobaldi from 3.1.2 to 3.1.3 with Windows installer, 
point-and-click does not seem to be working properly when a filename contains multibyte characters.

- When I click on the link from Music View, nothing happens.
- Cursor position in the editor is not synchronized.

These occur when the filename contains Japanese, i.e. multibyte characters.
- Working with music.ly / music.pdf , no problems.
- With おんがく.ly / おんがく.pdf , everything works fine except for the point-and-click.

I noticed that the tooltips on the links are displayed differently between 3.1.2 and 3.1.3.
In 3.1.3, the source filename embedded in the link is not decoded correctly.
(see red ovals below)

**3.1.2**
![image](https://user-images.githubusercontent.com/86141940/123503868-aa8e0180-d690-11eb-92ef-a57d846ee960.png)

**3.1.3**
![image](https://user-images.githubusercontent.com/86141940/123503870-b083e280-d690-11eb-8000-70d67cf9d3e6.png)

Is there any solution or workaround for this?

Is it possible that the change of bundled python from 3.5 to 3.6 is the cause?
[PEP 529 -- Change Windows filesystem encoding to UTF-8](https://www.python.org/dev/peps/pep-0529/)

**Comment by fedelibre** [comment]
@t-kitagishi Can you try with the latest version (3.3.0) and close this issue if you cannot reproduce the bug anymore?
Thanks

**Comment by t-kitagishi** [comment]
Works fine with frescobaldi 3.3.0. Thanks!
