### ISSUE TITLE
Frescobaldi-3.1.3-x86_64.dmg won't run on Mac OS 11.3.1 (Big Sur)

### ISSUE THREAD

**Issue by MichaelHendry** [frescobaldi/frescobaldi#1380]
...because it's not from the App Store nor from an identified developer.

**Comment by rpspringuel** [comment]
That's a question of your macOS security settings.  See [this support article](https://support.apple.com/en-us/HT202491) for instructions on how to create an exception to the security settings for Frescobaldi.

Given that this app is developed by volunteers in their free time, I would not expect them to ever become an "identified developer" as an Apple Developer account costs $99/year.

**Comment by dliessi** [comment]
Closing as "won't fix", since solving the issue would cost us money, as @rpspringuel noted. I'll add a link to the support article in the release page starting from the next release (due in few days).
