### ISSUE TITLE
No Midi playback options despite installing required packages

### ISSUE THREAD

**Issue by TheNomadicAspie** [frescobaldi/frescobaldi#1399]
I installed lilypond, python, pyqt5, python-ly, frescobaldi, python-poppler-qt5, and pygame.

When going to preferences, midi settings, it says "Midi through port-0" for player output. On the main screen, when trying to select the dropdown for "Midi" there are no options. Is there some other configuration I need to do to enable Midi playback?

I couldn't figure out how to install Python-PortMidi so as suggested on the Downloads page I used pygame instead. But is there something else I'm supposed to do, or some documentation that I'm not finding on how to do this?

**Comment by fedelibre** [comment]
#1148 might be the issue to track
