### ISSUE TITLE
Macros for changing notes on an existing rythm.

### ISSUE THREAD

**Issue by pysaumont** [frescobaldi/frescobaldi#1418]
Hi,

I use Frescobaldi to input Big Band scores from old paper scores. 70% of the work consists in entering voices for instruments that play the same rhythm with different notes. Entering the first instrument is ok (although it might be made easier with the help of some macros), but entering the other instrument in the same group (5 saxophones, 4 trumpets, and 4 trombones) is tedious. I have to enter all articulations, slurs, and everything in the first instrument in order for it to be reproduced, and then I have to change every single note. Double-clicking a note selects it, but it also selects the duration, which means that I have to retype it. It would be great to make digits word separators. I can also put a space between the note and the duration, but the document becomes more difficult to read since digits alone have different meanings depending on what comes before.

Having a possibility to "tab" top the next note and select it in a single operation (without selecting the duration) would be great. An even better workflow would be to select the first not (manually) then hit a note on the keyboard and it will replace the selected note without altering the duration and automatically jump to the next note and select it. This is what MuseScore does in "re-pitch" mode.

Another feature that would speed note entry would be to use the midi keyboard for all entries, and not only for notes. For example mapping notes in the lower range to duration, or any other midi events to any combination that is usually typed on the computer keyboard.

May be this can be done with existing macro packages (I am using Linux), or any means of application automation. Any information about in which direction to search is welcome. Of course, I could download the Frescobaldi sources and implement this myself, but I would have to learn so much to do this that it wouldn't be my first choice (nor my second or third, by the way!)

Thanks for this great application! I love it more and more each day.

**Comment by pysaumont** [comment]
Thanks, but I don't see how this is a solution.  The rhythm is explicitly specified in the three parts. I already use this technique to share many things between parts. But how could this work for rhythm? Note that if you remove the rhythm in musI and musII, it still works because the rhythm doesn't change. What would be ok is something like:

    \version "2.22.1"
    
    arts = { s8\p\< s4-. s8\! }
    
    musI = { c' c' c' }
    musII = { d' e' g'' }
    
    <<
      \new Voice << \arts \musI >>
      \new Voice << \arts \musII >>
    >>

But this doesn't work!

**Comment by Jean-Abou-Samra** [comment]
Sorry, I was in a hurry and looked at your problem too fast. How about doing this:

```
\version "2.22.1"

applyTemplate =
#(define-music-function (template music) (ly:music? ly:music?)
   (let* ((t-events (extract-typed-music template 'rhythmic-event))
          (t-length (length t-events))
          (m-events (extract-typed-music music 'rhythmic-event))
          (m-length (length m-events)))
     (if (not (eqv? t-length m-length))
         (ly:music-warning music
                           "mismatch: ~a notes/rests in template but ~a in music"
                           t-length
                           m-length))
     (for-each (lambda (t-ev m-ev)
                 (set! (ly:music-property m-ev 'duration)
                       (ly:music-property t-ev 'duration))
                 (set! (ly:music-property m-ev 'articulations)
                       (append (ly:music-property m-ev 'articulations)
                               (ly:music-property t-ev 'articulations))))
               t-events
               m-events)
     music))

template = { s8\p\< s4-. s8\! }

musI = { c' c'-> c' }
musII = { d' e' g'' }

<<
  \new Voice \applyTemplate \template \musI
  \new Voice \applyTemplate \template \musII
>>
```

**Comment by pysaumont** [comment]
Wow! That's a great improvement! I will try that on a full score tomorrow. I have made some modifications, but I really don't know if this is the best way to do it. I wanted to avoid having to enter the template with "s" because I can't see what is happening while I type. So I tried to use the first voice as a template.

Another problem is that sometimes, there are slight variations between voices. Most often, it is a not that is replaced with 2 notes, For this case, I introduced a new template which is a copy of the first one with the rhythmic variation. This is very fast because there is no need to change the notes:

      \version "2.22.1"
      
      applyTemplate =
      #(define-music-function (template music) (ly:music? ly:music?)
         (let* ((t-events (extract-typed-music template 'rhythmic-event))
                (t-length (length t-events))
                (m-events (extract-typed-music music 'rhythmic-event))
                (m-length (length m-events)))
           (if (not (eqv? t-length m-length))
               (ly:music-warning music
                                 "mismatch: ~a notes/rests in template but ~a in music"
                                 t-length
                                 m-length))
           (for-each (lambda (t-ev m-ev)
                       (set! (ly:music-property m-ev 'duration)
                             (ly:music-property t-ev 'duration))
                       (set! (ly:music-property m-ev 'articulations)
                             (append (ly:music-property m-ev 'articulations)
                                     (ly:music-property t-ev 'articulations))))
                     t-events
                     m-events)
           music))
          
          altoSaxI = { d'8\p\< e'4.-. g''2\! }
          
          altoSaxII = { c' c' c' }
          
          tenorSaxI = { c' b' g }
          
          tenorSaxII = { e f g }
          
          baritoneTemplate = { d'8\p\< e'4.-. s4 s\! }
          
          baritoneSax = { c' b a4 g }
          
          <<
            \new Voice \altoSaxI
            \new Voice \applyTemplate \altoSaxI \altoSaxII
            \new Voice \applyTemplate \altoSaxI \tenorSaxI
            \new Voice \applyTemplate \altoSaxI \tenorSaxII
            \new Voice \applyTemplate \baritoneTemplate \baritoneSax
          >>


The only drawback I see at this time is the difference between voices which might make reading the code a bit difficult. This can be solved by replacing the first voice with:

        \new Voice \applyTemplate \altoSaxI \altoSaxI

but this looks a bit weird.

Anyway, thanks a lot! That will really help.

**Comment by Jean-Abou-Samra** [comment]
Not sure I understand the problem with `s`, but be aware that there is no need for it -- modern LilyPond recognizes standalone durations just as well as standalone pitches.

For slight variations from the template you could use:

```
\version "2.22.1"

#(use-modules (srfi srfi-11))

#(define-tag-group '(untemplated))

untemplated =
#(define-music-function (replaces music) (index? ly:music?)
   (ly:music-set-property! music 'replace-count replaces)
   (tag 'untemplated music))

applyTemplate =
#(define-music-function (template music) (ly:music? ly:music?)
   (call/cc
    (lambda (abort)
     (let ((t-events (extract-typed-music template 'rhythmic-event)))
       (for-some-music
        (lambda (m)
          (cond
           ((memq 'untemplated (ly:music-property m 'tags))
            (let ((c (ly:music-property m 'replace-count)))
              (if (not (false-if-exception
                        (begin (set! t-events (drop t-events c))
                               #t)))
                  (begin
                    (ly:music-warning m "not enough notes/rests to skip in template")
                    (abort music))))
            #t)
           ((not (music-is-of-type? m 'rhythmic-event))
            #f)
           ((null? t-events)
            (ly:music-warning m "not enough notes/rests in template")
            (abort music))
           (else
            (let-values (((t rest) (car+cdr t-events)))
              (set! (ly:music-property m 'duration)
                    (ly:music-property t 'duration))
              (set! (ly:music-property m 'articulations)
                    (append (ly:music-property m 'articulations)
                            (ly:music-property t 'articulations)))
              (set! t-events rest))
            #f)))
        music)
       (if (pair? t-events)
           (ly:music-warning (car t-events)
                             "extraneous notes/rests in template")))
     music)))

template = { 8\p\< 4-. 8\! 16 32 }

musI = { c' c'-> c' c' c' }
musII = {
  d' e'
  \untemplated 1 {
    g'16 g\!
  }
  a b
}

<<
  \new Voice \applyTemplate \template \musI
  \new Voice \applyTemplate \template \musII
>>
```

`\untemplated` expects the number of notes to skip in the templates, and music that is inserted as-is without receiving a duration and articulations from the template.

**Comment by pysaumont** [comment]
That's absolutely fantastic! Thank you so much! I am working on a project about copying hundreds of old Big Band paper scores. That will divide the time needed by at least three. Thank you so much!

If I may, I have two additional questions. One is whether there is a way to use this code to produce the corresponding "normal" code that would have produced the same result. In other words, instead (or additionally) of producing the image of the score, it would produce this:
        
    musIexpanded = { c'8\p\< c'4-.-> c'8\! c'16 c'32 }
    musIIexpanded = { d'8\p\< e'4-. g'16 g\! a16 b32 }

The goal would be to produce a "simpler" source code that would be easier to use for people who don't know about Lilypond. (I am trying to persuade some of my fellow musicians to switch to Lilypond for their own scores, and although your example will be perfect for me, it might be a bit hard for them!)

My second question is about what is the language you use in your example. Is it Guile? I definitely want to learn that! Do you know about a good tutorial?

Again, thank you so much for your help. That will make my life so much easier in the coming months!

**Comment by Jean-Abou-Samra** [comment]
I realize now that my snippet did not work with chords. Here is a fixed version:

```
\version "2.22.1"

#(use-modules (srfi srfi-11))

#(define-tag-group '(untemplated))

untemplated =
#(define-music-function (replaces music) (index? ly:music?)
   (ly:music-set-property! music 'replace-count replaces)
   (tag 'untemplated music))

applyTemplate =
#(define-music-function (template music) (ly:music? ly:music?)
   (define (apply-duration! t m)
     (set! (ly:music-property m 'duration)
           (ly:music-property t 'duration)))
   (define (apply-articulations! t m)
     (set! (ly:music-property m 'articulations)
           (append (ly:music-property m 'articulations)
                   (ly:music-property t 'articulations))))
   (call/cc
    (lambda (abort)
     (let ((t-events (extract-typed-music template 'rhythmic-event)))
       (for-some-music
        (lambda (m)
          (cond
           ((memq 'untemplated (ly:music-property m 'tags))
            (let ((c (ly:music-property m 'replace-count)))
              (if (not (false-if-exception
                        (begin (set! t-events (drop t-events c))
                               #t)))
                  (begin
                    (ly:music-warning m "not enough notes/rests to skip in template")
                    (abort music))))
            #t)
           ((not (or (music-is-of-type? m 'event-chord)
                     (music-is-of-type? m 'rhythmic-event)))
            #f)
           ((null? t-events)
            (ly:music-warning m "not enough notes/rests in template")
            (abort music))
           (else
            (let-values (((t rest) (car+cdr t-events)))
              (if (music-is-of-type? m 'event-chord)
                  (begin
                    (for-each
                     (lambda (ev)
                       (apply-duration! t ev))
                     (ly:music-property m 'elements))
                    (apply-articulations! t m))
                  (begin
                    (apply-duration! t m)
                    (apply-articulations! t m)))
              (set! t-events rest)
              #t))))
        music)
       (if (pair? t-events)
           (ly:music-warning (car t-events)
                             "extraneous notes/rests in template")))
     music)))

template = { 8\p\< 4-. 8\!-. 16 32 }

musI = { c' c'-> <c' c''> c' c' }
musII = {
  d' e'
  \untemplated 1 {
    g'16 g\!
  }
  a b
}

<<
  \new Voice \applyTemplate \template \musI
  \new Voice \applyTemplate \template \musII
>>
```

By the way, others have come up with things like this before: https://lists.gnu.org/archive/html/lilypond-user/2019-11/msg00292.html, https://lsr.di.unimi.it/LSR/Item?id=465, https://lsr.di.unimi.it/LSR/Item?id=654 (none of these has something like `\untemplated` though).

To answer your questions: to format a music expression roughly as it would be entered, use `\displayLilyMusic`, which prints it into the log file (`\displayLilyMusic \applyTemplate ...`). This is documented at https://lilypond.org/doc/v2.23/Documentation/notation/displaying-lilypond-notation. It can't print *everything* (e.g. if you have Scheme code in the music), but it usually works pretty well.

And, yes, this is Scheme/Guile code. There is a Scheme tutorial in the official Extending manual at https://lilypond.org/doc/v2.23/Documentation/extending/index. Unfortunately it's somewhat sparse, so people have written others. I'm aware of https://scheme-book.ursliska.de/introduction/index.html in English (by Urs Liska, ambitious but incomplete), and https://tutoriel-scheme.readthedocs.io/ in French (by me, less ambitious but more complete in the topics it covers). You won't just need knowledge of the language but also of LilyPond's Scheme interfaces. These are covered, again sparsely, in the Extending manual, and quite more thoroughly https://extending-lilypond.readthedocs.io/ (by me too, in English this time). If you have questions about these, feel free to ask them on the lists (lilypond-user-fr@gnu.org in French or lilypond-user@gnu.org in English, see lilypond.org/contact).

**Comment by pysaumont** [comment]
Again, thanks a lot! This is absolutely perfect. I was wondering whether I should switch to MuseScore for this project in order to use their Re-pitch function, but this is far better. I just have now to fix some problems with Jazz chords and everything will be good. But first, I will spend some time with your Scheme/Lilypond tutorail.

A huge thank you for your help!

**Comment by Jean-Abou-Samra** [comment]
You're welcome. If you consider this resolved, it would be a good idea to close the issue so future people working on Frescobaldi won't be confused :-)
