### ISSUE TITLE
Producing multiple PDF

### ISSUE THREAD

**Issue by pysaumont** [frescobaldi/frescobaldi#1423]
Hi,

Is there a way for Frescobaldi to produce multiple PDFs from a single file? The goal is to produce one PDF for each instrument from a list of scores which are in separate documents. I can extract the individual parts from each document and group them, but I don't know how to produce one PDF per instrument (besides, of course, creating one source file per instrument, which I would like to avoid.)

The ideal solution would be to simply have a list of titles (corresponding to each tune) and automatically produce one PDF for each instrument (20 in my case), while avoiding any repetitive coding.

**Comment by Jean-Abou-Samra** [comment]
Have a look at http://lilypond.org/doc/v2.23/Documentation/notation/multiple-output-files-from-one-input-file.html.



At the end of the day, this is more a LilyPond question and not really related to Frescobaldi. It may be a better fit on lilypond-user or lilypond-user-fr.

**Comment by pysaumont** [comment]
Thanks for the link. I am now able to do it, although with much boilerplate that should be replaced with function calls (which I could make work until now!), but I would like to go further and allow non-technical users to select the tune names from a list, select the instruments involved, check the result is preview and produce the PDFs. I was thinking about extensions in Frescobaldi. Is it something possible?

**Comment by Jean-Abou-Samra** [comment]
Sorry, this went in my spam folder. Yes, it is possible, check https://github.com/frescobaldi-extensions.

**Comment by pysaumont** [comment]
Thanks. I think I just have to learn Python, now. That should be much easier than learning GUILE, I guess!
