### ISSUE TITLE
Play MIDI from cursor?

### ISSUE THREAD

**Issue by fgimian** [frescobaldi/frescobaldi#1424]
Hey there folks, absolutely love Frescobaldi!

I was wondering if it's possible to play MIDI from the cursor whereby the application determines the current bar and moves the transport of the MIDI player to that bar and continues playback?

This would be really helpful on longer scores when previewing a particular section later in the piece.

Huge thanks
Fotis

**Comment by fedelibre** [comment]
This has been discussed already in #71 and #1084

**Comment by fgimian** [comment]
> This has been discussed already in #71 and #1084

Oh cool, so sorry for the duplicate.  I'll close this one for now. 😄
