### ISSUE TITLE
Fresco 2.20 in place of Fresco 3.2

### ISSUE THREAD

**Issue by thiryjl** [frescobaldi/frescobaldi#1436]
I installed Frescobaldi 3.2 (Mac/ Mojave) following the procedure proposed in the “install” file. It worked fine and the application is called "Python", but the surprise is also in the info box which shows some rather fancy and far from expected version numbers:
––––––––– 
When opening Frescobaldi 3.2 I have the following infos :
_Fresco Baldi:_ **2.20.0**
Python: **3.5.9**
python-ly: 0.9.5
Qty: 4.8.7
PyQt: 4.12.1
sip: 4.19.20
poppler: 0.61.1
python-poppler-qt: 0.24.0
OS: Darwin-18.7.0-x86_64-i386-64bit
installation type: command line

What happened ? I don't think I've used a 2.20 version in the past that would have left traces on my Mac. 
–––––––––

––––––––– 
When opening Frescobaldi 3.0 info box says this:
_Fresco Baldi:_ **3.0.0**
Python: **3.7.0**
python-ly: 0.9.5
Qt: 5.11.1
PyQt: 5.11.2
sip: 4.19.12
poppler: 0.57.0
python-poppler-qt: 0.24.2
OS: Darwin-18.7.0-x86_64-i386-64bit
installation type: standalone app bundle

Which is normal
–––––––––
Why are there so many differences? what is good? wrong?

**Comment by fedelibre** [comment]
> When opening Frescobaldi 3.2 I have the following infos : _Fresco Baldi:_ **2.20.0** Python: **3.5.9** python-ly: 0.9.5 Qty: 4.8.7 PyQt: 4.12.1 sip: 4.19.20 poppler: 0.61.1 python-poppler-qt: 0.24.0 OS: Darwin-18.7.0-x86_64-i386-64bit installation type: command line
> 
> What happened ? I don't think I've used a 2.20 version in the past that would have left traces on my Mac.

Well, it's possible. I cannot remember when Qt4 was dropped, but it was a long time ago.

I think you did something wrong when building. I'm closing this issue, feel free to write to the mailing list if you need help with installing Frescobaldi on Mac.

**Comment by dliessi** [comment]
@fedelibre For the record, I helped Jean Louis off-list and off-GitHub to fix his Frescobaldi installation.
