### ISSUE TITLE
Function that counts the number of notes, pauses, dynamic tickets entered, etc. number.

### ISSUE THREAD

**Issue by flash-gordonxx** [frescobaldi/frescobaldi#1437]
Dear developers
I have been using frescobaldi for a long time and I would be very happy with such a feature.
Thank you for making it happen! :)

(Function that counts the number of notes, pauses, dynamic tickets entered, etc. number.)

**Comment by Jean-Abou-Samra** [comment]
That sounds more like a job for LilyPond than the editor you use to interact with it, e.g.

```
\version "2.22.2"

printStats =
#(define-music-function (music) (ly:music?)
   (let ((notes 0)
         (rests 0)
         (dynamics 0))
     (for-some-music
      (lambda (m)
        (cond
         ((music-is-of-type? m 'note-event)
          (set! notes (1+ notes)))
         ((or (music-is-of-type? m 'rest-event )
              (music-is-of-type? m 'multi-measure-rest-event))
          (set! rests (1+ rests)))
         ((music-is-of-type? m 'dynamic-event)
          (set! dynamics (1+ dynamics))))
        #f)
      music)
     (ly:message "Found ~a notes, ~a rests and ~a absolute dynamics" notes rests dynamics)
     music))

\printStats \relative c' { c'4\mf\< e r8 g4 b c1\ff }
```

What is the usefulness of this, though?

**Comment by flash-gordonxx** [comment]
> That sounds more like a job for LilyPond than the editor you use to interact with it, e.g.
> 
> ```
> \version "2.22.2"
> 
> printStats =
> #(define-music-function (music) (ly:music?)
>    (let ((notes 0)
>          (rests 0)
>          (dynamics 0))
>      (for-some-music
>       (lambda (m)
>         (cond
>          ((music-is-of-type? m 'note-event)
>           (set! notes (1+ notes)))
>          ((or (music-is-of-type? m 'rest-event )
>               (music-is-of-type? m 'multi-measure-rest-event))
>           (set! rests (1+ rests)))
>          ((music-is-of-type? m 'dynamic-event)
>           (set! dynamics (1+ dynamics))))
>         #f)
>       music)
>      (ly:message "Found ~a notes, ~a rests and ~a absolute dynamics" notes rests dynamics)
>      music))
> 
> \printStats \relative c' { c'4\mf\< e r8 g4 b c1\ff }
> ```
> 
> What is the usefulness of this, though?

Does this code help solve the problem? I ran it but nothing happens.

**Comment by Jean-Abou-Samra** [comment]
Look at the console output.

**Comment by Jean-Abou-Samra** [comment]
What do you mean? What is ‘LilyPond-Protocol’? Sorry, I don’t understand, please elaborate.

**Comment by flash-gordonxx** [comment]
`https://1drv.ms/u/s!AspI3B3yd-hBgbOnUrFxwrgnEZ7GD6c?e=kOHHij`

That's what I was thinking.

**Comment by Jean-Abou-Samra** [comment]
Ah, yes. In English, "LilyPond-Protokoll" would be translated as "LilyPond console output" or "LilyPond log" :-)

On your screenshot, after the line "Fehler: Programm zu alt…", there is "Found 5 notes, 1 rests and 2 absolute dynamics", namely, in German, "5 Notes, 1 Pausen und 2 Modifizierungen gefunden" (my German is rusty, so the translation might be sloppy).

**Comment by flash-gordonxx** [comment]
Now I understand and thank you. But I don't know where to put it in other pieces?

**Comment by Jean-Abou-Samra** [comment]
It goes before a music expression. For example, if you have a `\score` block, you could put it on that block's main music expression to count all notes in the piece.

```
\score {
  \printStates { music ... }
  \midi { }
  \layout { }
}
```

By the way, I'm still curious: what are you going to use this for?

**Comment by flash-gordonxx** [comment]
`https://1drv.ms/u/s!AspI3B3yd-hBgbOnU3BB1xWdQZA_zCU?e=5Nu1pA`


Can you put me in this File? Wherever I copied it responded with an error message.

I'm sorry, but I'd rather write the score than deal with the program.
Your answer is: I plan to write a sheet music to order and I will calculate the price based on the characters I enter.

**Comment by Jean-Abou-Samra** [comment]
See attached file.

[Fresco1437.zip](https://github.com/frescobaldi/frescobaldi/files/8743225/Fresco1437.zip)


If you considered this solved, please remember to close the issue (I'm not a developer on this project, so I can't do it).

**Comment by flash-gordonxx** [comment]
It works great. :)
If the request is not too high, could the \ cresc \ decresc \ dim \ breathe \ fermata signs be counted? :)

**Comment by Jean-Abou-Samra** [comment]
Sure. See this:

```
\version "2.22.2"

#(use-modules (ice-9 match))

statDefinitions =
#'(
   ;; notes
   ("notes" note-event)
   ;; rests (including multi-measure rests)
   ("rests" rest-event multi-measure-rest-event)
   ;; dynamics: absolute dynamics (like \p), dynamic spans (like \cresc)
   ("dynamics" dynamic-event span-dynamic-event)
   ;; articulations: \staccato, \prall, \fermata, ...
   ("articulations" articulation-event)
   ;; \breathe
   ("breath marks" breathing-event)
   ;; basically count everything
   ("events" event)
   )

printStats =
#(define-music-function (music) (ly:music?)
   (for-each
    (match-lambda
     ((desc . classes)
      (let ((count 0))
        (for-some-music
         (lambda (m)
           (if (any (lambda (c)
                      (music-is-of-type? m c))
                    classes)
               (set! count (1+ count)))
           #f)
         music)
        (ly:message "| Found ~a ~a" count desc))))
    statDefinitions)
   music)
                  

\printStats \relative c' { c'4-.\mf\< e-. r8 \breathe g4-. b-. c1\ff\fermata }
```

It lets you define what stats you want to print. In `statDefinitions`, the first element of each sublist is the description of what is being counted, used in the log message. The other elements are "event classes" that are matched. For a list of possible event classes, see https://lilypond.org/doc/v2.23/Documentation/internals/music-classes.

**Comment by flash-gordonxx** [comment]
Thank you very much :)
