### ISSUE TITLE
Port to Qt5

### ISSUE THREAD

**Issue by andrewbernard** [frescobaldi/frescobaldi#1454]
It's difficult if not impossible to build F on Alma Linux as support for Qt4 was dropped from RHEL in 2015. While it may be a big project, would it be possible to consider building with Qt5 at least?

**Comment by dliessi** [comment]
Frescobaldi moved to Qt5 with version 3.0.0 (released 17 February 2017).

**Comment by andrewbernard** [comment]
Thank you. In my stupidity I was reading the section Frescobaldi 2!

Andrew
