### ISSUE TITLE
Is lilypond 2.23.14 supported?

### ISSUE THREAD

**Issue by nvictor** [frescobaldi/frescobaldi#1459]
Hello,

I downloaded `lilypond 2.23.14` to try a new feature but I am getting the following error when engraving. Is that version supported? How can I get a more verbose log? Thank you.

```
Starting lilypond 2.23.14 [preuve.ly]...Aborting lilypond 2.23.14 [preuve.ly]...
Exited with return code 15.
```

My specs are:

```
Frescobaldi: 3.2
Extension API: 0.9.0
Python: 3.9.9
python-ly: 0.9.7
Qt: 5.15.6
PyQt: 5.15.2
sip: 4.19.24
qpageview: 0.6.2
poppler: 21.6.1
python-poppler-qt: 0.75.0
OS: Linux-5.19.0-76051900-generic-x86_64-with-glibc2.33
```

The OS is `Pop!_OS 22.04 LTS 64-bit`

**Comment by nvictor** [comment]
Sorry for the late reply @Jean-Abou-Samra. 

Here's the output from command line.

```bash
➜  Projects cd lilypond-2.23.14 
➜  lilypond-2.23.14 ls
bin  etc  lib  libexec  licenses  share  test.ly
➜  lilypond-2.23.14 cat test.ly        
\version "2.23.14" { c' }
➜  lilypond-2.23.14 ./bin/lilypond test.py
GNU LilyPond 2.23.14 (running Guile 2.2)
warning: cannot find file: `test.py'
fatal error: failed files: "test.py"
➜  lilypond-2.23.14 cd bin             
➜  bin ./lilypond ../test.py
GNU LilyPond 2.23.14 (running Guile 2.2)
warning: cannot find file: `../test.py'
fatal error: failed files: "../test.py"
➜  bin mv ../test.ly .                                        
➜  bin ./lilypond test.py   
GNU LilyPond 2.23.14 (running Guile 2.2)
warning: cannot find file: `test.py'
fatal error: failed files: "test.py"
```

It's complaining about not being able to find the input file. Did I do it wrong?

**Comment by nvictor** [comment]
@Jean-Abou-Samra Double post. Sorry. But it occurs to me that the working directory was probably wrong. So I did

```bash
➜  lilypond-2.23.14 PATH=. ./bin/lilypond test.ly 
GNU LilyPond 2.23.14 (running Guile 2.2)
Processing `test.ly'
Parsing...
Interpreting music...
Preprocessing graphical objects...
Finding the ideal number of pages...
Fitting music on 1 page...
Drawing systems...
Converting to `test.pdf'...
Success: compilation successfully completed
➜  lilypond-2.23.14 ls
bin  etc  lib  libexec  licenses  share  test.ly  test.pdf
```

This was what I got.

**Comment by fedelibre** [comment]
@nvictor Are you using the flatpak package of Frescobaldi? (I see the versions in your specs are the same)

If the answer is yes, how did you add version 2.23.14? BTW, I'm building a new Frescobaldi flatpak including v2.23.14 right now.

**Comment by nvictor** [comment]
@fedelibre That is correct! I added 2.23.14 by going to the settings.
![lilypond](https://user-images.githubusercontent.com/76629/194943223-ec26540e-77d8-4962-9048-5952b39677cb.png)

**Comment by fedelibre** [comment]
You might notice the weird path recorded by Frescobaldi: `/run/user/1000/doc/...`. It means that you put the lilypond binaries in a path where Frescobaldi flatpak doesn't have full permissions, so lilypond binary won't work. You have two options:

1. Move the binaries in one of the supported locations: `~/Documents`, `~/Downloads`, `~/Music` (see [flatpak manifest](https://github.com/flathub/org.frescobaldi.Frescobaldi/blob/master/org.frescobaldi.Frescobaldi.yaml#L24)).
2. Use the Flatseal app to grant the permissions for the directory you're currently using.

This issue has been recently discussed [here](https://github.com/flathub/org.frescobaldi.Frescobaldi/issues/10).

**Comment by nvictor** [comment]
@Jean-Abou-Samra oh my god! :open_mouth:

@fedelibre Thanks will try that!

**Comment by nvictor** [comment]
@Jean-Abou-Samra @fedelibre it worked after I moved the binaries to `~/Downloads` :+1: :+1: 

Thanks a lot for your help!
