### ISSUE TITLE
partCombine autocomplete string outdated

### ISSUE THREAD

**Issue by aogzpa** [frescobaldi/frescobaldi#1471]
`\partCombine` autocomplete string should be camelCased as per the actual stable version, but it remains lowercased yet (`\partcombine`)

https://lilypond.org/doc/v2.23/Documentation/notation/multiple-voices#automatic-part-combining

**Comment by aogzpa** [comment]
> Note that this is not a typo: `\partCombine` used to be called `\partcombine` before LilyPond 2.21.0.

Oh, that's right!
Maybe we can include both?

**Comment by PeterBjuhr** [comment]
Could you rename the commit aswell to reflect the change on the Lilypond side?

**Comment by dliessi** [comment]
Fixed in #1472
