### ISSUE TITLE
Frescobaldi installed from MacPorts has Python main menu

### ISSUE THREAD

**Issue by Jean-Abou-Samra** [frescobaldi/frescobaldi#1481]
On the lilypond-user-fr list, user reported that when installing Frescobaldi from Macports, the application's main menu is that of the Python launcher or something like that.

![image](https://user-images.githubusercontent.com/37271310/204556250-678657cc-1dc7-43d6-9757-e692803b14d5.png)

CC @dliessi, maybe you already have an idea what's going on?

**Comment by fedelibre** [comment]
It looks familiar. Very similar to the Wayland issue.
I don't think that MacOS follows the Freedesktop standard though.

**Comment by dliessi** [comment]
This is expected when Frescobaldi is launched form the Terminal
There is no workaround.
The only way to have Frescobaldi as menu name is to launch Frescobaldi using the application bundle: if installed via MacPorts, the application bundle is in /Applications/MacPorts.

I'm removing the "defect" label and closing the issue on the assumption that Frescobaldi was launched via the Terminal.
If this is not the case, please reopen the issue (and possibly add the "defect" label again, although I suspect that even in that case this is something out of our control).
