### ISSUE TITLE
cannot install 3.3.0 on Windows

### ISSUE THREAD

**Issue by fedelibre** [frescobaldi/frescobaldi#1580]
I've just tried a fresh install on Windows 10 and I get this error at startup:

![Schermata del 2023-04-04 13-57-06](https://user-images.githubusercontent.com/1644647/229786212-5889e428-aa65-4b26-9f91-8c86eb7ccfec.png)

> ImportError: DLL load failed while importing QtCore

@19joho66

**Comment by 19joho66** [comment]
I needed to find a computer where I could do a fresh install to reproduce this issue as well as issue #1579. For this issue there is a .dll missing which I will provide with the next setup.

**Comment by fedelibre** [comment]
I've installed the latest installer and now I can launch Frescobaldi!
