### ISSUE TITLE
.ly is missing by saving

### ISSUE THREAD

**Issue by Musix** [frescobaldi/frescobaldi#16]
hi there

when i save e.g. "song1" in frescobaldi 2.0.1, it saves as "song1" instead of "song1.ly". i think, the .ly should be added automatically (manually is ok)

best regards

musix

**Comment by wbsoft** [comment]
Now Frescobaldi uses a default filename when saving a document for the first time, with an extension added. Does this help in these cases?

**Comment by uliska** [comment]
It is much less likely to happen as (only) the 'untitled' is pre-selected. So when I click 'Save' and start entering a filename the `.ly` is kept.

But still when I enter a name without extension the file is saved without extension (on Debian/Gnome).

**Comment by fedelibre** [comment]
I'm testing Frescobaldi 3.3.0 (flatpak) on Fedora 38 (GNOME) and when I save a new file the (GTK4) file dialog proposes *Untitled.ly* (where Untitled is focused so I can start typing and change the file name without losing the .ly extension).

We should check other desktop environments and operating systems and see if we can close this issue.

**Comment by fedelibre** [comment]
3.3.0 behaves correctly even on Windows (10):

![immagine](https://github.com/frescobaldi/frescobaldi/assets/1644647/96b1fc60-0a64-4295-92b5-589635601603)
