### ISSUE TITLE
Investigate QtPdf

### ISSUE THREAD

**Issue by jeanas** [frescobaldi/frescobaldi#1691]
While nifty, python-poppler-qt5 is a constant source of build, installation and distribution pain for us because Python packaging has poor overall support for native libraries.

I've recently learnt that recent Qt versions have a built-in module for PDF rendering. See https://doc.qt.io/qt-5.15/qtpdf-index.html. I think it would be interesting to investigate whether we could use it. I suspect the answer will be no, but if it was reasonably easy, it could win us a lot of relief.

**Comment by bmjcode** [comment]
It looks like Qt 6 has added PDF hyperlink support via [QPdfLinkModel](https://doc.qt.io/qt-6/qpdflinkmodel.html). I'm presuming we'll have to port Frescobaldi to Qt 6 at some point anyway, so would this be worth re-investigating?

**Comment by bmjcode** [comment]
Point-and-click now works in my Qt 6 port. This required some major changes to qpageview as well as Frescobaldi, so if you want to test it make sure you have the latest versions of both.

**Comment by bmjcode** [comment]
Merged in #1780.
