### ISSUE TITLE
Frescobaldi crashes when attempting to print music to PDF using MS "Print to PDF"

### ISSUE THREAD

**Issue by emseedee** [frescobaldi/frescobaldi#1711]
As title, small un-re-sizeable popup window (with a title bar "Print....      ?" appears when attempting to print music using Microsoft "Print to PDF" pseudo-printer, and Frescobaldi hangs until killed. It is possible to print the source to PDF using this printer, and it is also possible to print music to PDF using CutePDF writer.

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.4
python-ly: 0.9.7
Qt: 5.15.2
PyQt: 5.15.4
sip: 6.6.2
qpageview: 0.6.2
poppler: 20.12.1
python-poppler-qt: 21.3.0
OS: Windows-10-10.0.22631

**Comment by emseedee** [comment]
User error - works OK when score has been engraved for publication.

**Comment by fedelibre** [comment]
I've just tried using the "Print to PDF" option in Linux. Frescobaldi (flatpak) doesn't hang but the PDF was not created.

Which command is used under the hoods? lpr maybe?

**Comment by bmjcode** [comment]
This looks to be specific to the Microsoft Print to PDF and XPS Document Writer pseudo-printers on Windows. I don't yet know for sure, but I suspect it's in either qpageview or Qt itself rather than Frescobaldi. It's still a problem under Qt 6.
