### ISSUE TITLE
Score Wizard creates deprecated Lilypond statements

### ISSUE THREAD

**Issue by antimatter84** [frescobaldi/frescobaldi#1717]
When creating a new score file with the Score Wizard it will use the following statement in the code:

    \override Stem #'neutral-direction = #'()

Starting from Lilypond 2.23 this will show a warning during compilation:

    warning: deprecated: missing `.' in property path Stem.neutral-direction
    \override Stem 
                   #'neutral-direction = #'()

Using the following notation will not show the deprecation warning:

    \override Stem.neutral-direction = #'()

**Comment by ksnortum** [comment]
This seems to be a bit of a rabbit hole.  There are a lot of places where Frescobaldi creates LilyPond source code, and a simple search and replace won't do.  I'm working on a pull request for this.

**Comment by fedelibre** [comment]
closed by #1718
