### ISSUE TITLE
frescobaldi version 3.3.0 is not up to date 

### ISSUE THREAD

**Issue by JohnKSellers** [frescobaldi/frescobaldi#1725]
The current stable release of Lilypond is 2.24.3
The Frescobaldi version 3.3.0 is only current to 2.24.1

The current download at https://www.frescobaldi.org/download is 3.3.0

**Comment by fedelibre** [comment]
Frescobaldi and LilyPond are packaged separately.
What you write doesn't make sense. You can use whatever version of LilyPond you want.
