### ISSUE TITLE
AttributeError: module 'functools' has no attribute 'cache'

### ISSUE THREAD

**Issue by fgohier** [frescobaldi/frescobaldi#1726]
hello,
just after the start of frescobaldi, I want to check the lilypond version : when I click on "Settings", the exception below occurs

Traceback (most recent call last):
  File "/home/moi/git/frescobaldi/frescobaldi_app/preferences/__init__.py", line 163, in slotCurrentItemChanged
    item.activate()
  File "/home/moi/git/frescobaldi/frescobaldi_app/preferences/__init__.py", line 181, in activate
    w = self._widget = self.widget(dlg)
  File "/home/moi/git/frescobaldi/frescobaldi_app/preferences/__init__.py", line 218, in widget
    from . import lilypond
  File "/home/moi/git/frescobaldi/frescobaldi_app/preferences/lilypond.py", line 60, in <module>
    @functools.cache
AttributeError: module 'functools' has no attribute 'cache'

Optionally describe below what you were doing:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.8.10
Git branch: master
on commit: 7391df98
python-ly: 0.9.5
Qt: 5.12.8
PyQt: 5.14.1
qpageview: 0.6.0
poppler: 0.80.0
python-poppler-qt: 0.24.2
OS: unknown
Installation kind: distro package or installed from source

**Comment by fgohier** [comment]
more precisely : Menu Edit / Preferences / Lilypond preferences

**Comment by fedelibre** [comment]
> Python: 3.8.10

What's your distro? You are using an old version of Python. `functools.cache` was introduced in Python 3.9.x. See the [doc](https://docs.python.org/3/library/functools.html).

@jeanas Should we bump the minimum Python version from 3.8 to 3.9?

**Comment by jeanas** [comment]
It's my fault, sorry. Fixed in 7ab050a5a88c27222f7e5a133dca0cb49b846462.

**Comment by jeanas** [comment]
(@fedelibre Let's not drop Python 3.8 before it's unsupported upstream?)

**Comment by fedelibre** [comment]
> (@fedelibre Let's not drop Python 3.8 before it's unsupported upstream?)

Ok, I agree. I see you found a better fix for now.
