### ISSUE TITLE
LilyPond overrides with pre-2.18 syntax

### ISSUE THREAD

**Issue by ksnortum** [frescobaldi/frescobaldi#1728]
As per David Kastrup in the LilyPond users' forum:

> Calling
> 
>     git grep "\\\\override[^=]*#'[a-z]"
> 
> in the current Frescobaldi source tree delivers _way_ too many hits.

Search for all "bad" overrides in the code base and bring them up to post-2.18 syntax, for instance:

    \override Tie #'thickness = #2

becomes

    \override Tie.thickness = #2

And a way should be found to fix any overrides that span line breaks.

**Comment by jeanas** [comment]
Should be fixed. Please reopen if you find a missing spot.

**Comment by ksnortum** [comment]
There's a "clever" one hidden in two lines in clef_treble_8.ly, lines 7 and 8.  (Sorry, I don't know how to re-open the issue.)

**Comment by jeanas** [comment]
Ah yes, fixed in b6bc6e8a3a13f0e235a0c463555f8769990995e4.

> (Sorry, I don't know how to re-open the issue.)
