### ISSUE TITLE
Confusing Lilypond upgrade

### ISSUE THREAD

**Issue by hallmerle** [frescobaldi/frescobaldi#1739]
I installed and used Lilypond a long time ago on an earlier version of Ubuntu (now Ubuntu 20.04.6 LTS).  Since I now have time to use it more, I thought I should upgrade to the current stable release.  So, I downloaded that and it's simply a package file which the docs say to just unpack.  I have no idea where to extract the files to.  My current install is 2.20.0:

```
$ whereis lilypond
lilypond: /usr/bin/lilypond.real /usr/bin/lilypond /usr/lib/x86_64-linux-gnu/lilypond /usr/share/lilypond /usr/share/man/man1/lilypond.1.gz

$ ls /usr/lib/x86_64-linux-gnu/lilypond/2.20.0/
bin  guile  python
```

I certainly wouldn't have manually extracted the previous version into /usr/lib/x86_64-linix-gnu.  Is that where the new version should go?

I did look in Ubuntu Software to see if there was a newer version, and it only displays Frescobaldi which when installed doesn't upgrade Lilypond but simply points to the current install.  I see in the Preferences where to point to a newer version wherever it ends up.

Any clarification would be helpful.  Thanks!

**Comment by jeanas** [comment]
Don't extract it into `/usr/` (or do anything you don't *perfectly understand* in `/usr/`, for that matter), put it somewhere in your home folder instead. Have you seen the tutorial https://lilypond.org/doc/v2.24/Documentation/learning/graphical-setup-under-gnu_002flinux.html?

**Comment by hallmerle** [comment]
Yes, I wasn't going to put it in /usr as, like I said, I wouldn't normally
put anything there anyway.

I thought I had looked at that page in the docs, but must not have as it
did clarify what I need to do.

Sorry to bother folks!

Thank you!
