### ISSUE TITLE
api-ms-win-core-path-l1-1-0.dll missing

### ISSUE THREAD

**Issue by ferret-28** [frescobaldi/frescobaldi#1752]
I still have Win-7 Professional x64 SP1, with automatic updating enabled. 
Among the currently installed programs are: Microsoft.Net Framework 4.7.2 and 4.8 along with the different Microsoft Visual C++ 2008, 2015, 2015x86, 2015-2022 redistrib., 2022x64 addit. and minimum.
The following problem occured when launching Frescobaldi 3.3.0 for the first time: a system warning message telling  "The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer."

I decided first to uninstall Frescobaldi 3.3.0 before asking here for some advice. I didn't found the required dll neither in System32 folder nor in SysWOW64. Nevertheless I got the 32-bit and the 64-bit versions of this dll from:
https://github.com/nalexandru/api-ms-win-core-path-HACK/releases

I just wonder if introducing these missing dll's in the system folders would finally allow Frescobaldi 3.3.0 to run under my  Win-7 Professional x64 SP1 
(the 32-bit version goes into SysWOW64, and the 64-bit version goes into System32).

Thanks in advance for your answers.

**Comment by jeanas** [comment]
Sorry, Frescobaldi doesn't support Windows 7, if only because current versions of both Python and LilyPond don't support it.

**Comment by ferret-28** [comment]
What versions of Frescobaldi and Lilypond would nevertheless run on Windows 7 ?
This would help me until i upgrade my OS.

**Comment by jeanas** [comment]
For LilyPond, 2.22 or earlier. For Frescobaldi, I don't know, sorry.
