### ISSUE TITLE
Freezes on restart

### ISSUE THREAD

**Issue by bishopcranmer** [frescobaldi/frescobaldi#1757]
On an M2 MacBook Air, Sonoma 14.4.1, 16 gigs of memory, nearly 600 Gb of free space on the hard drive, when restarting Frescobaldi after a previous use, the main screen appears but does not "paint" the menu at the top, nor does it react to the mouse. One must task switch to Finder and then Force Quit and restart the computer to restart Frescobaldi. I'm running version 3.3.0. I've tried both Intel and ARM versions with the same results.

**Comment by jeanas** [comment]
This seems like an instance of #428.
