### ISSUE TITLE
Icon file name of fresobaldi is not compatible with linux mint/cinnamon

### ISSUE THREAD

**Issue by MartinP1** [frescobaldi/frescobaldi#1769]
The icon with file name "org.frescobaldi.Frescobaldi.svg" is not displayed in task bar, when using cinnamon desktop / linux mint.
See https://github.com/linuxmint/cinnamon-desktop/issues/242

Instead the system Icon "gear" is displayed.

Developer response there is...

>  The problem here is not the number of dots in the name as many icon names have more than one. I think the problem is the capital "F" which is not allowed according to Freedesktop's Icon Naming Specification:
> 
> `    As a further restriction, all icon names may only contain lowercase letters, numbers, underscore, dash, or period characters.`
> 
> Best to report bug to app developer I think.

Personally I have "repaired" it by creating a copy of "org.frescobaldi.Frescobaldi.svg" -> "frescobaldi.svg", and changed icon in menu setting

**Comment by fedelibre** [comment]
As discussed on the issue mentioned above, this is not a Frescobaldi issue.
