### ISSUE TITLE
Can't generate a score.

### ISSUE THREAD

**Issue by ctptincomp** [frescobaldi/frescobaldi#1777]
When I try to generate a score, I get this message in the log:

Starting lilypond 2.24.4 [lilytest.ly]...
Processing `/Applications/lilypond-2.24.4/bin/lilytest.ly'
Parsing...
Interpreting music...
Preprocessing graphical objects...
Finding the ideal number of pages...
Fitting music on 1 page...
Drawing systems...
Converting to `lilytest.pdf'...
warning: g_spawn_sync failed (-1): gs: Failed to execute child process “gs” (No such file or directory)
warning: `(gs -q -dNODISPLAY -dNOSAFER -dNOPAUSE -dBATCH -dAutoRotatePages=/None -dPrinted=false /var/folders/3h/1sbkgzld5b3bnrrfqq6rdd2h0000gs/T//lilypond-tmp-7157280)' failed (-1)

[/Applications/lilypond-2.24.4/share/lilypond/2.24.4/ly/init.ly:65:2](https://github.com/frescobaldi/frescobaldi/issues/0): error: Guile signaled an error for the expression beginning here
#
 (let ((book-handler (if (defined? 'default-toplevel-book-handler)
Throw to key `ly-file-failed' with args `()'.
Exited with return code 1

What is "gs"? g_spawn_sync? What can I do?

Thanks for your help.

--Noob.

**Comment by fedelibre** [comment]
gs is Ghostscript, one of LilyPond dependencies.

Please follow the official [instruction guide](http://lilypond.org/doc/v2.24/Documentation/learning/graphical-setup-under-macos.html), in particular the part about enabling ghostscript in the Mac System preferences.

I'll close this issue.
