### ISSUE TITLE
<Please summarize your bug or feature request>

### ISSUE THREAD

**Issue by Dominik6641** [frescobaldi/frescobaldi#1791]
Ich wollte gerade versuchen einen Code in Frescobaldi auszugeben aber das geht mit der Versionsangabe nicht nur ich weiß nicht wieso bei der Version 2.24.4 hat das funktioniert mit der Versionsangabe aber warum das jetzt nicht bei der Version 3.3.0 funktioniert könnt ihr mir da helfen

**Comment by Dominik6641** [comment]
und eigentlich müsste das da doch auch funktionieren

**Comment by jeanas** [comment]
Vielleicht verwechseln Sie die Version von LilyPond, 2.24.4, mit der Version von Frescobaldi, 3.3.0?

**Comment by Dominik6641** [comment]
das ist richtig damit das mit dem Ausgeben funktioniert nehme ich diese Versionsangabe: Version "2.22.2"
________________________________
Von: Jean Abou Samra ***@***.***>
Gesendet: Dienstag, 17. September 2024 18:18
An: frescobaldi/frescobaldi ***@***.***>
Cc: Dominik6641 ***@***.***>; Author ***@***.***>
Betreff: Re: [frescobaldi/frescobaldi] <Please summarize your bug or feature request> (Issue #1791)


Vielleicht verwechseln Sie die Version von LilyPond, 2.24.4, mit der Version von Frescobaldi, 3.3.0?
