### ISSUE TITLE
Frescobaldi 3.3.0 freezes upon loading on MacOS 14.6.1

### ISSUE THREAD

**Issue by yoshiakionishi** [frescobaldi/frescobaldi#1793]
Hello—

When I launch Frescobaldi on my computer, about 50% of the time it freezes (even though Frescobaldi's screen may appear, it won't go into the app even when I click on it), and when I try to force quit, the app says "not responding." The other time, it opens, though it is necessary to click the icon on the menu bar to properly see the window. I know that this topic has been discussed in the cases of MacOS [Ventura](https://github.com/frescobaldi/frescobaldi/issues/1704) and [Big Sur](https://github.com/frescobaldi/frescobaldi/issues/1336), but I don't see one in Sonoma, which I am using currently. (I highly doubt I will be upgrading to Sequoia any time soon).

The Frescobaldi Version info:

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.10.14
python-ly: 0.9.7
Qt: 5.15.12
PyQt: 5.15.10
sip: 6.8.6
qpageview: 0.6.2
poppler: 24.1.0
python-poppler-qt: 21.3.0
OS: macOS-14.6.1-arm64-arm-64bit
installation kind: standalone .app bundle

I am using Macbook Pro with M2 Max Chip, if it is helpful.

Please advise if I need to rectify any of the installed components. Grateful in advance for your help!

**Comment by ericrood** [comment]
Hi,

Same issue on my Mac Mini with M2 Pro and Mac OS 14.6.1 with Frescobaldi 3.3.0.

After launching Frescobaldi most of the time the Frescobaldi menu does not appear. The screen stays empty until I click on the Frescobaldi icon again (known issue). When the GUI screen appears, mostly the menubar does not and I have to Force Quit and try again. (Often more than five tries, so very annoying). Once the program is working it stays stable (except most of my shortkeys doesn't work , but that is probably another issue).

I hope there is a workaround for this problem.

Thanks in advance.
Eric

**Comment by jeanas** [comment]
This is almost the same problem as #428.

Some users have reported that launching Frescobaldi from a terminal worked for them (which is consistent with the fact that the issue seems caused by the GUI wrapper generated by py2app).

**Comment by ericrood** [comment]
Thanks.
I tried to open the app by the terminal but the pogram still freezes during startup.

**Comment by jeanas** [comment]
What command did you run?

**Comment by jeanas** [comment]
Sorry for not being clear, but this isn't the command I meant. I don't recall how exactly the app bundles are structured, and I don't have a macOS machine, but you have to find the `python` executable and the `frescobaldi` script inside, and run the former on the latter.

**Comment by yoshiakionishi** [comment]
Wow! Thank you @jeanas for the pointer. Now the application opens perfectly.

Here is how I did it.

1. Go to `Applications` folder and find Frescobaldi.app
2. Secondary click on the icon --> choose `Show Package Contents`
3. Go to: `Contents` --> `MacOS`
4. Double click `Frescobaldi` 
5. Terminal opens, then Frescobaldi opens subsequently.
6. To quit the application, either closing the terminal window, going to menu bar's `Frescobaldi`-->`Quit Frescobaldi` or the keystroke command+q works. It won't close from the icon on the Dock on the Desktop.

If you like, creating an alias of `Frescobaldi` in Item 4 and moving it to the desktop or elsewhere would allow you to open the app without having to go through the above process.

**Comment by ericrood** [comment]
Thank you @yoshiakionishi and @jeanas .
This workaround works fine for me too.
