### ISSUE TITLE
[Feature request] Engrave on save

### ISSUE THREAD

**Issue by asimard1** [frescobaldi/frescobaldi#1798]
When saving a file, it would be nice to have an option to engrave everytime, just like Overleaf does for LaTeX.

Having it engrave at every modification is painful since it often causes the pdf to not produce and brings you back to page one. Maybe that could be fixed as well, like save the location in the PDF and stay there.

**Comment by ksnortum** [comment]
Just so I can understand... (I don't know how Overleaf works.)

If you engrave the file, it saves first.  So if you want to save and engrave, you can just press Ctrl-M or click the engrave button on the toolbar.  Is this what you want, or something different?

**Comment by jeanas** [comment]
> If you engrave the file, it saves first.

Not by default, but there's an option for it in Edit > Preferences > LilyPond Preferences which I think should answer the OP's request.

**Comment by asimard1** [comment]
I have tried the option, but it seems a little bit inconsistent. I have had some cases where I engrave but it does not save the file, but it is not a big problem.
