### ISSUE TITLE
"Save All" button

### ISSUE THREAD

**Issue by DWW256** [frescobaldi/frescobaldi#1799]
(feature request)

Could you add a button that saves every unsaved open file?  And can you map the keyboard shortcut Ctrl+Shift+S to it?  This shortcut is in Visual Studio, and I would find it very useful here!  Thanks

**Comment by jeanas** [comment]
Isn't this File > Save > Save All?

You can add a custom shortcut for it in Edit > Preferences > Keyboard Shortcuts.

**Comment by fedelibre** [comment]
By default `Ctrl+Shift+S` will "Save as". It's the same default I see in VSCodium (open source version of Visual Studio).
You'll have to delete that shortcut to be able to use it for Save all.

I'll close this issue.
