### ISSUE TITLE
Floating Music View window on Frescobaldi

### ISSUE THREAD

**Issue by BenjiSlucky** [frescobaldi/frescobaldi#1805]
I accidentally closed the Music View pane and when I activated it again under the Tools menu, it only appeared as an external window which can no longer be docked into the main program window.

Is there a solution?

Unfortunately, a complete de- and reinstallation of the program did not help.

Thanks,
Benjamin

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.12.3
python-ly: 0.9.7
Qt: 5.15.14
PyQt: 5.15.11
sip: 6.8.6
qpageview: 0.6.2
poppler: 24.2.0
python-poppler-qt: 21.3.0
OS: Linux-6.8.0-47-generic-x86_64-with-glibc2.39

**Comment by jeanas** [comment]
This is #1273 (thus closing as duplicate) and should ultimately be fixed by #1780.

As a workaround for now, you may manually edit the file `~/.config/frescobaldi/frescobaldi.conf` to remove the `[mainwindow]` section.

**Comment by BenjiSlucky** [comment]
Great! Thank you so much, it works now ;-)
