### ISSUE TITLE
Change Copy to Image to use PNG only?

### ISSUE THREAD

**Issue by bmjcode** [frescobaldi/frescobaldi#1811]
The Copy to Image dialog provides a choice of file types, but only PNG and JPEG are currently supported under Qt 6 because of QtPdf limitations. Copying to any of the vector formats -- SVG, PDF, and EPS -- requires Poppler to work.

Even under Frescobaldi 3.3.0, only PNG and JPEG work for what seems like an obvious use case: copy-and-pasting a selection from Frescobaldi to LibreOffice Writer. (I may be wrong on this, but I think the [OOoLilyPond extension](https://github.com/OOoLilyPond) also uses PNG for that reason.)

And since JPEG's lossy compression is poorly suited to musical scores, PNG is really the only sensible choice left.

Does anyone object to this change?

**Comment by jeanas** [comment]
I think it's fine. We're very unlikely to produce any new versions of Frescobaldi that relies on Poppler anyway.

**Comment by bmjcode** [comment]
Implemented in #1815.
