### ISSUE TITLE
No Music view after update.

### ISSUE THREAD

**Issue by Musicpal** [frescobaldi/frescobaldi#1824]
Did a update yesterday, today i notice that music view from Frescobaldi is gone.
Also after a renwed engrave (Ctrl+Shift+M)
Log reposrt does show that a new file is made without error and the slider goes from 1 to 100%

![Frescobaldi-music-view](https://github.com/user-attachments/assets/ba74be15-bd6f-4328-b479-d4f10628abe0)

Frescobaldi: 3.3.0
Extension API: 0.9.0
Python: 3.11.10
python-ly: 0.9.8
Qt: 5.15.14
PyQt: 5.15.11
sip: 6.8.6
qpageview: 0.6.2
poppler: unknown
python-poppler-qt: unknown
OS: Linux-6.11.8-1-default-x86_64-with-glibc2.40

**Comment by bmjcode** [comment]
Do you have python-poppler-qt5 installed? If I had to guess, maybe your Python version got upgraded but you don't have that package installed under the new version.

**Comment by Musicpal** [comment]
> Do you have python-poppler-qt5 installed? If I had to guess, maybe your Python version got upgraded but you don't have that package installed under the new version.

Thank you.
python311-poppler-qt5 was/is installed and now also installed python310-poppler-qt5, no difference.

**Comment by fedelibre** [comment]
If you run `frescobaldi` from a terminal, do you see any useful information? Which Linux distro are you using? Did you install frescobaldi from the distro repository?

**Comment by fedelibre** [comment]
> Using openSUSE Tumbleweed 20241124.

I would ask for help [here](https://forums.opensuse.org/).

**Comment by jeanas** [comment]
What's the output from `python -c 'import popplerqt5'? Maybe there is a weird error during import that is being swallowed.

You installed Frescobaldi from your distro's package, right? Not in a virtual environment (including with `pipx`)?

**Comment by Musicpal** [comment]
```
% python3.11 -c 'import popplerqt5'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /lib64/libQt5Core.so.5: version `Qt_5_PRIVATE_API' not found (required by /home/neljor/.local/lib/python3.11/site-packages/PyQt5/QtCore.abi3.so)
```

Yes: Distribution: openSUSE Tumbleweed
Not a virtual environment.

**Comment by jeanas** [comment]
Yeah, so that's it. You have an installation of PyQt5, probably made with pip, which conflicts with the system one. Please remove it. `pip uninstall PyQt5` should do. You can also use `pip list --user` to check which packages you have installed in this way

**Comment by Musicpal** [comment]
Thanks for this!

Found the solution.
Because i installed a rmbg with python, python got messed up.

Have removed all the python packages from the $HOME directory.

Thanks and have a great day.
