### ISSUE TITLE
planned: LilyPrompt (was: wish: "lisp")

### ISSUE THREAD

**Issue by Musix** [frescobaldi/frescobaldi#29]
hi there,

do you know lisp? this porgrammer language compiles immadiatly when programming. so, what about such a "function" for frescobaldi in the future? i mean ... you write "c4 d e f g2 g a4 a a a g1" and frescobaldi will engrave only these notes - "realtime"  - and adds this to the existing notes?!

this would be a very luxury feature. no basic feature, but something for frescobaldi V3.0 ?! :)

greetings.

**Comment by uliska** [comment]
I would say #345 warrants closing this one. Please reopen if you disagree @wbsoft.
