### ISSUE TITLE
Supporting External Libraries

### ISSUE THREAD

**Issue by uliska** [frescobaldi/frescobaldi#599]
This issue was partially discussed in #592 but it was (rightly so) suggested to open a dedicated issue for it.

There are things an editor/IDE could do with LilyPond scores that is not in the Python domain but that works on the LilyPond side. The basic approach is somehow injecting LilyPond code in the to-be-compiled score.

As an example we have the Layout Control Modes that work that way. For this we have some LilyPond files in the `layoutcontrol` directory. But this approach works only because we don't require any code to be persistent in the LilyPond files.

However, there are things that only work together with code inside the LilyPond files. One example (from my current interest) are annotations that can be entered in LilyPond files using my new [ScholarLY](https://github.com/openlilylib/scholarly) library. I would like to add an GUI for these annotations (annotation editor, annotation browser, context menu integration etc.) because it would be absolutely terrific to have such annotation editing integrated in Frescobaldi
Of course we could include the relevant library code into Frescobaldi like we did with the Layout Control Modes. But that would mean that the files can only be compiled with Frescobaldi - which is of course an inacceptable situation.

So the idea for a solution is to "support" external libraries. That means Frescobaldi "knows" whether a user has a certain library installed and can accordingly provide functionality. So if Frescobaldi knows that, say, ScholarLY is available it can enable related functionality such as the annotation editor and otherwise hide it in some way (by removing menu items or panels, or by greying them out).

There are three approaches we could consider:
- Create a dedicated "Frescobaldi library" and make it publicly available separately from Frescobaldi (like python-ly). This may be the cleanest solution.
- Support _one_ existing library, presumably openLilyLib. The problem with this is that openLilyLib is by now rather shapeless, and through its quite open attitude it's also comparably volatile.
- Support arbitrary libraries. This would mean that any given functionality would depend on a given library. The responsibility for such support would be on the side of the Frescobaldi developers, not on that of the users.

It may be of interest in this context that currently we also have discussions about creating specifications for writing libraries in a consistent way. The hope is that this encourages people to upload their personal solutions and make them more generally available. The overall hope is that one day we'll have an ecosystem of extension packages similar to that of LaTeX (although much smaller of course).

**Comment by PaulMorris** [comment]
Another possibility for discussion would be to develop a plugin architecture for Frescobaldi (more or less like browser plugins or wordpress plugins).  Then Frescobaldi could continue to support just LilyPond's core functionality, while plugins could provide additional functionality.  Plugins could involve both Scheme and Python code, extending both Frescobaldi and LilyPond.  For example, a plugin could provide the kinds of integration, GUI interfaces, etc. that Urs describes for his ScholarLY library.  The plugins could be updated independently without requiring new releases of Frescobaldi.

**Comment by uliska** [comment]
Am 28.01.2015 um 03:52 schrieb PaulMorris:
>
> Another possibility for discussion would be to develop a plugin 
> architecture for Frescobaldi (more or less like browser plugins or 
> wordpress plugins). Then Frescobaldi could continue to support just 
> LilyPond's core functionality, while plugins could provide additional 
> functionality. Plugins could involve both Scheme and Python code, 
> extending both Frescobaldi and LilyPond. For example, a plugin could 
> provide the kinds of integration, GUI interfaces, etc. that Urs 
> describes for his ScholarLY library. The plugins could be updated 
> independently without requiring new releases of Frescobaldi.
>
>

Sounds reasonable. I especially like the idea of updating plugins 
independently.
This would also alleviate the implications of *Frescobaldi* depending on 
some LilyPond libraries. Although: It already depends on a lot of 
things. What I'd suggest is more or less the same as with python-ly: 
Develop a library that Frescobaldi depends on and then make that library 
easily available so any LilyPond user can use it.

**Comment by PeterBjuhr** [comment]
Here are some thoughts:

As mentioned in #592 I agree with @PaulMorris on using a plugin architecture (although 'extension' is perhaps a more correct phrase than 'plugin'). But I lean towards the idea that we should develop the present Snippets functionality rather than creating a new architecture (if that was implied).

I think we should be careful to make the distinction between LilyPond code that extends the capabilities of the released LilyPond code, and Python code that rely on those additional LilyPond libraries being present. 

Furthermore I think all LilyPond extensions should be optional, but of course easy to add on and well documented. It could be great add-ons for those who choose to use them, but they shouldn't be mandatory.

If the LilyPond extensions are optional, it's reasonable that also the Python code is (hence we can call them Python extensions).

We already have the functionality to add optional LilyPond extensions, but perhaps we need to develop it further!??

And as mentioned at the top, we already have Snippets for Python extensions; but here I see a greater need for further development.

@uliska what do you say of this model where LilyPond extensions and Python extensions go in pair? Is it somehow awkward to separate the functionality in this way? I think it is the cleanest solution because we want to support both LilyPond extensions and Python extensions that doesn't have this connection.

**Comment by uliska** [comment]
Am 28.01.2015 um 12:10 schrieb Peter Bjuhr:
>
> Here are some thoughts:
>
> As mentioned in #592 
> <https://github.com/wbsoft/frescobaldi/issues/592> I agree with 
> @PaulMorris <https://github.com/PaulMorris> on using a plugin 
> architecture (although 'extension' is perhaps a more correct phrase 
> than 'plugin'). But I lean towards the idea that we should develop the 
> present Snippets functionality rather than creating a new architecture 
> (if that was implied).
>

Well, what I proposed (on the Python side) is adding Python code that 
only gets enabled when the necessary LilyPond dependencies are met. I 
think this mostly does what you want already. But of course I wouldn't 
mind if that would be consolidated with an explicit infrastructure, be 
it "plugin" or "extension" or "snippet".

> I think we should be careful to make the distinction between LilyPond 
> code that extends the capabilities of the released LilyPond code, and 
> Python code that rely on those additional LilyPond libraries being 
> present.
>

Yes. AFAICS the problem is mainly with LilyPond code, that is decide 
about how these dependencies should be managed. Python code relying on 
LilyPond code would automatically be optional. So I don't think it would 
be strictly necessary to have an infrastructure to achieve that.

> Furthermore I think all LilyPond extensions should be optional, but of 
> course easy to add on and well documented. It could be great add-ons 
> for those who choose to use them, but they shouldn't be mandatory.
>

Yes, definitely. I think it would be a red line if we'd want to 
implement *fundamental* tools that would require external LilyPond code 
to be present or that would - given we include that code in Frescobaldi 
itself - make documents rely on being compiled with Frescobaldi.

> If the LilyPond extensions are optional, it's reasonable that also the 
> Python code is (hence we can call them Python extensions).
>

Well, as said, the Python code could easily be made optional automatically.
However, it may be a good idea regarding the interface that such 
optional functionality should have to be enabled explicitly.
Say, there's a Preference panel saying: Enable plugin X (or "download 
and enable plugin X"). In this process Frescobaldi could check the 
dependency and assist the user in acquiring a LilyPond library that is 
needed for the plugin.

> We already have the functionality to add optional LilyPond extensions, 
> but perhaps we need to develop it further!??
>

What do you mean by that, are you talking about the Layout Control Options?
There is one more thing we have to differentiate: Do LilyPond extensions 
rely on actual code in the documents themselves? The Layout control 
options don't need that, they can be activated simply by injecting the 
code upon compilation. Annotations only make sense when they are 
actually inserted in a document. So this document can only be compiled 
(in Frescobaldi or not) when the library code is present on the user's 
system.

> And as mentioned at the top, we already have Snippets for Python 
> extensions; but here I see a greater need for further development.
>

Can snippets be used to create panels?

> @uliska <https://github.com/uliska> what do you say of this model 
> where LilyPond extensions and Python extensions go in pair? Is it 
> somehow awkward to separate the functionality in this way? I think it 
> is the cleanest solution because we want to support both LilyPond 
> extensions and Python extensions that doesn't have this connection.
>

I'm not really sure if I understand you correctly.

**Comment by PeterBjuhr** [comment]
>>@uliskawhat do you say of this model
 where LilyPond extensions and Python extensions go in pair? Is it
 somehow awkward to separate the functionality in this way? I think it
 is the cleanest solution because we want to support both LilyPond
 extensions and Python extensions that doesn't have this connection.

>I'm not really sure if I understand you correctly.

Never mind, you answered my thoughts thoroughly! :)

**Comment by PeterBjuhr** [comment]
>>We already have the functionality to add optional LilyPond extensions,
 but perhaps we need to develop it further!??

>What do you mean by that, are you talking about the Layout Control Options?

I'm talking about adding LilyPond code by Include paths.

>There is one more thing we have to differentiate: Do LilyPond extensions
rely on actual code in the documents themselves? The Layout control
options don't need that, they can be activated simply by injecting the
code upon compilation. Annotations only make sense when they are
actually inserted in a document. So this document can only be compiled
(in Frescobaldi or not) when the library code is present on the user's
system.

If the Layout control code was removed from Frescobaldi, you could still use the functionality because the (LilyPond) code is also in OpenLilyLib. But it would take more manual labour to include everything in the LilyPond compilation (and you'd of course need to include the OpenLilyLib code).

I guess the situation is similar with annotations? The real magic happens in the LilyPond compilation but Frescobaldi can help setting everything up (and it's nice if Frescobaldi recognise keywords etc.). Or have I missed something?

I'm not sure that it's relevant for what we're discussing now if the LilyPond extension require a trigger in the document (annotations) or work in the background (layout control).

**Comment by PeterBjuhr** [comment]
@uliska I also like to emphasize that if I propose to have any additions as extensions outside Frescobaldi proper (I agree the Layout Control stays at least until the reorganisation is finished), that is not in any way a critique against your work (which I think is great and can be helpful for many users of Frescobaldi and LilyPond). 

We're only discussing proper organisation here, and doesn't judge the content!

**Comment by uliska** [comment]
Am 28.01.2015 um 13:27 schrieb Peter Bjuhr:
>
>         We already have the functionality to add optional LilyPond
>         extensions,
>         but perhaps we need to develop it further!??
>
>     What do you mean by that, are you talking about the Layout Control
>     Options?
>
> I'm talking about adding LilyPond code by Include paths.
>

OK.

>     There is one more thing we have to differentiate: Do LilyPond
>     extensions
>     rely on actual code in the documents themselves? The Layout control
>     options don't need that, they can be activated simply by injecting the
>     code upon compilation. Annotations only make sense when they are
>     actually inserted in a document. So this document can only be compiled
>     (in Frescobaldi or not) when the library code is present on the user's
>     system.
>
> If the Layout control code was removed from Frescobaldi, you could 
> still use the functionality because the (LilyPond) code is also in 
> OpenLilyLib. But it would take more manual labour to include 
> everything in the LilyPond compilation (and you'd of course need to 
> include the OpenLilyLib code).
>

Yes, that's exactly the point of my request to support external libraries.
The example of the layout control is actually a good example because it 
shows the problem of that appraoch: The code in openlilylib and in 
Frescobaldi is not the same. If it were to be the same it would have to 
be maintained in parallel - which is obviously not a good idea.
The same goes for the edition-engraver. This is a tool which I'd 
definitely want to use to add editing features in Frescobaldi (e.g. for 
conditional breaks: say you are working with two different manuscipts 
(or a manuscript and an original edition) you could switch from one to 
the other in the to-be-written manuscript viewer and automatically have 
LilyPond compile the score with the breaks of the respective manuscript. 
Or all the partial compilation stuff that will rely on the 
edition-engraver).
If we make a copy and maintain it in Frescobaldi it won't be consistent 
with the development of the original tool.

> I guess the situation is similar with annotations? The real magic 
> happens in the LilyPond compilation but Frescobaldi can help setting 
> everything up (and it's nice if Frescobaldi recognise keywords etc.). 
> Or have I missed something?
>

No, that's exactly what I mean.
And if such (compilation or editing) features rely on LilyPond code to 
be present in the file we must find a way to reliably address that code.

> I'm not sure that it's relevant for what we're discussing now if the 
> LilyPond extension require a trigger in the document (annotations) or 
> work in the background (layout control).
>

Yes, it does.
When we don't need actual code in the document (layout control, 
edition-engraver) it is "only" a matter of having to duplicate code into 
Frescobaldi, but when there's a need to persistently change the document 
we *need* to have the code in an external library - because otherwise 
that document would become dependent on being compiled with Frescobaldi.

**Comment by PeterBjuhr** [comment]
>When we don't need actual code in the document (layout control,
edition-engraver) it is "only" a matter of having to duplicate code into
Frescobaldi, but when there's a need to persistently change the document
we *need* to have the code in an external library - because otherwise
that document would become dependent on being compiled with Frescobaldi.

Good point! But it only adds the other reasons for having the code in external libraries.

Going back to my initial question, do you think the current functionality of adding external libraries (as include paths) is sufficient?

**Comment by PeterBjuhr** [comment]
>>And as mentioned at the top, we already have Snippets for Python
 extensions; but here I see a greater need for further development.

>Can snippets be used to create panels?

I'm not sure. But I think the main point is that Snippets was designed for small (python) scripts (hence the name, right @wbsoft ?) And for that purpose it's brilliant in my opinion. But it's not optimal for larger python extensions. (Maybe we should keep the Snippets as is after all, I'm not totally decided yet...)

**Comment by uliska** [comment]
Am 28. Januar 2015 15:27:29 MEZ, schrieb Peter Bjuhr <notifications@github.com>:
>>When we don't need actual code in the document (layout control,
>edition-engraver) it is "only" a matter of having to duplicate code
>into
>Frescobaldi, but when there's a need to persistently change the
>document
>we *need* to have the code in an external library - because otherwise
>that document would become dependent on being compiled with
>Frescobaldi.
>
>Good point! But it only adds the other reasons for having the code in
>external libraries.
>
>Going back to my initial question, do you think the current
>functionality of adding external libraries (as include paths) is
>sufficient?
>

No, that's why I raised this issue in the first place.
I think we need a way to use additional LikyPond code. I see (again) the option of providing one Frescobaldi lib that anybody can install separately if they don't use Frescobaldi.  Or supporting external libraries.

One thought that has come to ne in another thread is that we (= LilyPond, not Frescobaldi) could organize one main meta repository  (instead of a package manager), with more specialized libraries in directories. That way anybody would only have to download / clone one repository and have access to all code. So we could make some Python functonality in Frescobaldi depend on the installation of this single entity.
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by PeterBjuhr** [comment]
>>Can snippets be used to create panels?

>[...] But I think the main point is that Snippets was designed for small (python) scripts [...]

I should add that it's mainly for text manipulation of the LilyPond source code.

**Comment by PeterBjuhr** [comment]
>>Do you think the current functionality of adding external libraries (as include paths) is
sufficient?

>No, that's why I raised this issue in the first place.
I think we need a way to use additional LilyPond code. I see (again) the option of providing one Frescobaldi lib that anybody can install separately if they don't use Frescobaldi.  Or supporting external libraries.

>One thought that has come to me in another thread is that we (= LilyPond, not Frescobaldi) could organize one main meta repository  (instead of a package manager), with more specialized libraries in directories. That way anybody would only have to download / clone one repository and have access to all code. So we could make some Python functionality in Frescobaldi depend on the installation of this single entity.

Now perhaps we're closing in on the core of things. But I must ask you to expand upon that thought. There's already OpenLilyLib, and all the functionality can be included very easily in present design.

**Comment by uliska** [comment]
Yes, openlilylib may be a solution, particularly with the currently suspended reorganization.

We could either
- make openlilylib one library within the new super-repository or
- make openlilylib itself the new super-repository and move all content one level down.

I think the latter may be the solution.

**Comment by PaulMorris** [comment]
> On Jan 28, 2015, at 6:10 AM, Peter Bjuhr <notifications@github.com> wrote:
> 
> As mentioned in #592 <https://github.com/wbsoft/frescobaldi/issues/592> I agree with @PaulMorris <https://github.com/PaulMorris> on using a plugin architecture (although 'extension' is perhaps a more correct phrase than 'plugin’).

I just wanted to suggest this as another possibility for consideration, not necessarily to advocate for it over what Urs was suggesting.  

It seems to me that plugins/extensions would offer some advantages (like updating independently from Frescobaldi) but it would also take some significant work to implement the infrastructure for them, which may or may not be worth it.  

In a sense Urs is suggesting “built-in extensions" to Frescobaldi that are only activated when a given library is present, so this would be to take the next step, moving that code to extensions that can be maintained and updated separately.  

Different extensions could either contain their own LilyPond code or depend upon external LilyPond libraries (or Python libraries for that matter).

Different extensions could depend on users entering things into their LilyPond files (as with annotations) or not (as with layout-controls, edition-engraver).

> But I lean towards the idea that we should develop the present Snippets functionality rather than creating a new architecture (if that was implied).

I didn’t intend to imply anything either way on this, as I don’t know enough about it to know what would be best.  

To do what Urs wants the extensions would have to be able to add new GUI elements (menu items, panels, context menus, etc.) which I believe takes us quite beyond what snippets can do currently.

Of course, another possibility is to try to integrate some of this new functionality into LilyPond itself, and then there’s no problem with Frescobaldi using it.

**Comment by uliska** [comment]
>
>To do what Urs wants the extensions would have to be able to add new
>GUI elements (menu items, panels, context menus, etc.) which I believe
>takes us quite beyond what snippets can do currently.
>
>Of course, another possibility is to try to integrate some of this new
>functionality into LilyPond itself, and then there’s no problem with
>Frescobaldi using it.
>

I've more ir less given up on that.  It' inacceptably hard to get anything into LilyPond. Some stuff isn't appropriate to be included in Lily itself. And Frescobakdi would then have to manage its functionality depending on the used Lily version - which doesn't look less complicated at all.

If we have just *one* repository containing an arbitrary number of sub-projects I think the complexity of managing the dependency should be acceptablem

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by wbsoft** [comment]
> To do what Urs wants the extensions would have to be able to add new GUI elements (menu items, panels, context menus, etc.) which I believe takes us quite beyond what snippets can do currently.

Indeed. But we could design an infrastructure to make solid Frescobaldi extensions. That would not be snippets, but modules that can add to the GUI, panels etc. That would also require overhaul of the panelmanager, menu, actions etc. I propose to do that for Frescobaldi 3.0. Basic idea is that many Frescobaldi modules will be implemented themselves as extensions, which makes it easy to learn how to extend Fresc.

**Comment by PeterBjuhr** [comment]
Sounds really good to me!

**Comment by uliska** [comment]
LGTM too. Although it moves away from the question of supporting LilyPond libraries. Wrt that I think I'll give the one-openlilylib-with-submodules a go and come back to Frescobaldi when I have somethong concrete.

**Comment by PaulMorris** [comment]
> On Jan 28, 2015, at 11:56 AM, Urs Liska <notifications@github.com> wrote:
> 
> >Of course, another possibility is to try to integrate some of this new
> >functionality into LilyPond itself, and then there’s no problem with
> >Frescobaldi using it.
> 
> I've more ir less given up on that. It' inacceptably hard to get anything into LilyPond. Some stuff isn't appropriate to be included in Lily itself.

I hear you, although I’d love to see at least the edition engraver eventually make its way into LilyPond proper, after it has been developed and refined independently for awhile.  

> And Frescobakdi would then have to manage its functionality depending on the used Lily version - which doesn't look less complicated at all.

Well, isn’t this already the situation?  Assuming that in any case LilyPond will gain new features that Frescobaldi would probably want to use or build upon?=

**Comment by PaulMorris** [comment]
Sounds good to me.

**Comment by uliska** [comment]
I've just glanced over this discussion, but I think it can be closed, now that we do have the Extension API implemented.
