### ISSUE TITLE
Icons not shown on Windows at all

### ISSUE THREAD

**Issue by proski** [frescobaldi/frescobaldi#670]
It's a tricky bug to reproduce, but I have seen it on two different Windows systems. Windows 7 was used in both cases. The bug goes away after installing seemingly unrelated software.

That's how the bug was reproduced the last time:

Uninstall all versions of Python and all Python libraries, remove Python directories.
Install 32-bit Python 2.7.9 using https://www.python.org/ftp/python/2.7.9/python-2.7.9.msi
Install PyQt from http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.3/PyQt4-4.11.3-gpl-Py2.7-Qt4.8.6-x32.exe
Check out frescobaldi and python-ly from their git repositories.
Install python-ly by `python setup.py develop --user`
Run `python frescobaldi` in the Frescobaldi directory.

Frescobaldi starts, the icons are not shown. After installing Python 3.4 and PyQt for Python 3.4, the problem went away even if Python 2 was still used to run Frescobaldi.

**Comment by wbsoft** [comment]
maybe Qt4 does not correctly find the `iconengines` plugins (those are in som Qt4 folder). Has Windows rebooted after installing the Qt stuff?. Is no single icon displayed, not even the symbols in the quick insert panel?

**Comment by proski** [comment]
There were no reboots as I wrote the report. But now I booted Windows and I can reproduce the problem again. Python 2.7 has the problem, python 3.4 shows the icons correctly. The menu icons are not shown, but the symbols are.

![noicons](https://cloud.githubusercontent.com/assets/1317472/6859628/e519b84e-d412-11e4-8330-59f0addc4d10.png)
