### ISSUE TITLE
Create a Tools->Viewers submenu

### ISSUE THREAD

**Issue by uliska** [frescobaldi/frescobaldi#753]
By now we have three viewers: Music View, Manuscript View and SVG View. And more might come (e.g. the Pre-View as suggested in #569).

It might be more consistent to create a submenu in the Tools section where all viewers can be combined. What do you think @PeterBjuhr and @wbsoft  (or anybody else)?

**Comment by PeterBjuhr** [comment]
A submenu makes the menu items harder to access so I wonder what is the reason for this change?

>It might be more consistent[...]

There are now other submenus among the tools so are you thinking about consistency in regards to the pitch, rhythm etc menus?

I think the relevant reason should be that the list of tools is growing too long...

**Comment by uliska** [comment]
There is a trade-off between "complexity" of additional navigation to a
submenu and having to "browse" a flat list of more or less unrelated items.
In my perception the "Tools" list (i.e. the generated list of
dockpanels) has already become too long and crowded, and the additional
manuscript viewer is just that extra bit that is too much. And
considering that there might (probably will) be even more viewer entries
in the future I found it's time to add that extra level.

However, this is probably very much a matter of taste or expectations,
that's why I didn't simply push this on our branch but opened a PR.

**Comment by PeterBjuhr** [comment]
Grouping all viewers is of course an obvious way of creating a submenu. Another possible grouping is the MIDI player and MIDI input. 

A less obvious way of thinking is to try to keep easy access to tools that is expected to be opened often and put the other tools in (a) submenu(s).

The contextmenu with a list of tools is growing equally and could also be considered in this regard.

**Comment by uliska** [comment]
I won't delete the `viewers-menu` branch although I closed the PR (#754). We'll consider this after the manuscript viewer is merged.

**Comment by uliska** [comment]
This has now long be done.
