### ISSUE TITLE
OSX: Frescobaldi overrides critical cursor navigation keyboard shortcuts

### ISSUE THREAD

**Issue by mauritslamers** [frescobaldi/frescobaldi#860]
Under OSX, Frescobaldi overrides certain keyboard combinations which are critical to the text editor. 

The ones I have found so far:
- Cmd+arrow left: Should move the cursor to the beginning of the current line. Instead switches to the previous open file.
- Cmd+arrow right. Should move the cursor to the end of the current line. Instead switches to the next open file.

**Comment by wbsoft** [comment]
Those defaults are defined in `mainwindow.py` around line 1180, using `QKeySequence.Back` and `QKeySequence.Forward`, which on mac os x should map to Ctrl+[ and Ctrl+] (see http://doc.qt.io/qt-4.8/qkeysequence.html#standard-shortcuts ). Strange that they seem to map to Alt+Left and Alt+Right (is Alt Cmd on Mac OS X?)

**Comment by mauritslamers** [comment]
Alt is not Cmd on OSX, Cmd is the same as the super / windows key.
The Cmd-arrow left and Cmd-arrow right are system wide default keyboard shortcuts to go to the beginning of the current line, and the end of the current line.

Looking at the linked document: what this issue is about, is that the commands described in the linked document as MoveToStartOfLine and MoveToEndOfLine don't seem to be honored.
