### ISSUE TITLE
Adding a "replace mode" to MIDI Input

### ISSUE THREAD

**Issue by Stemby** [frescobaldi/frescobaldi#866]
I'd like to have this implementation:
1. click before notes you'd like to replace
2. activate the "Replace mode" on the MIDI Input interface
3. play the MIDI keyboard

Frescobaldi should replace old notes with the new ones.

It would represent the solution for closing the second part of #839 .

**Comment by AlexSchr** [comment]
To some extend, this feature already exists, albeit the other way round than you suggest.
WIth the menu entry "Tools => Rhythm => Apply rhythm" one can replace the rhythm of a sequence of notes. For some workflows, the menu entries "Copy/Paste rhythm" might be useful, instead.

**Comment by deviskra** [comment]
The last one commit worked fine for the last time for me. There were slurs, ties, graces, dynamics many voices (with <<{} \\ {} >> syntax) and all the time it replaced chords and notes correctly. Much faster to type this way, especially if there are many chords. So, don't use later commits for tests.

**Comment by fedelibre** [comment]
Fixed by #1152
