### ISSUE TITLE
add AppStream metainfo file

### ISSUE THREAD

**Issue by fedelibre** [frescobaldi/frescobaldi#879]
December 2019 update: the term appdata has been replaced by metainfo in AppStream spec, so I'm changing the title accordingly. More importantly, the expected file is `$PREFIX/share/metainfo/%{id}.metainfo.xml`.

[AppStream spec](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) allows to define some information on the project that can be read and used by different software centers (GNOME Software, KDE Discover, AppCenter).

As Frescobaldi has no AppData file, when I find Frescobaldi in GNOME Software it appears without screenshots nor any other information:

![schermata da 2016-12-23 17-27-15](https://cloud.githubusercontent.com/assets/1644647/21458233/18dbd7b6-c935-11e6-8754-1d0bc127ccbe.png)

This screenshot was made 3 years ago. As of 2019 Frescobaldi is not visible anymore on GNOME Software.

**Comment by fedelibre** [comment]
I'm trying to make a patch, just to see how it works (I'll probably have to leave it to some real developer). I cannot understand how to copy the `frescobaldi.appdata.xml` file to the proper install location. I've added this line to setup.py:

```
$ git diff
diff --git a/setup.py b/setup.py
index 9af67d7..bf9e834 100644
--- a/setup.py
+++ b/setup.py
@@ -57,6 +57,7 @@ else:
         ('share/icons/hicolor/scalable/apps', ['frescobaldi_app/icons/frescobaldi.svg']),
         ('share/applications', ['frescobaldi.desktop']),
         ('share/man/man1', ['frescobaldi.1']),
+        ('share/metainfo/', ['frescobaldi.appdata.xml']),
     ]
 
 setup_extra_args = {}
```

but then the file is copied to the python install directory, e.g. `/usr/lib/python3.5/site-packages/frescobaldi-3.0.0-py3.5.egg/share/metainfo/frescobaldi.appdata.xml`. But it should be relative to the install path, that is in /usr or /usr/local (or whatever is chosen by the user).

**Comment by fedelibre** [comment]
Before I forget about this, for those who want to test it, this is a basic file:

```
<component type="desktop-application">
​  <id>frescobaldi</id>
​  <metadata_license>CC0</metadata_license>
​  <project_license>GPL-2.0+</project_license>
​  <name>Frescobaldi</name>
​  <summary>LilyPond Music Editor</summary>
​
​  <description>
​    <p>
​      Frescobaldi is an advanced text editor to edit LilyPond sheet music files.
      It aims to be powerful, yet lightweight and easy to use.
​    </p>
​    <p>Features:</p>
​    <ul>
​      <li>Powerful text editor with syntax highlighting and automatic completion</li>
​      <li>Music view with advanced Point &amp; Click</li>
      <li>Midi player to proof-listen LilyPond-generated MIDI files</li>
      <li>Midi capturing to enter music</li>
      <li>Powerful Score Wizard to quickly setup a music score</li>
      <li>Snippet Manager to store and apply text snippets, templates or scripts</li>
      <li>Use multiple versions of LilyPond, automatically selects the correct version</li>
      <li>Built-in LilyPond documentation browser and built-in User Guide</li>
      <li>Smart layout-control functions like coloring specific objects in the PDF</li>
      <li>MusicXML, Midi and ABC import</li>
      <li>Modern user interface with configurable colors, fonts and keyboard shortcuts</li>
      <li>Translated into the following languages: Dutch, English, French, German, Italian, Czech, Russian, Spanish, Galician, Turkish, Polish, Brazillian Portugese and Ukrainian.</li>
​    </ul>
​    <p>
​      Frescobaldi is designed to run on all major operating systems (Linux, Mac OS X
      and MS Windows). It is named after Girolamo Frescobaldi (1583-1643), an Italian
      composer of keyboard music in the late Renaissance and early Baroque period.
​    </p>
​  </description>
​
​  <screenshots>
​    <screenshot type="default">
​      <caption>Main editor view with PDF preview</caption>
​      <image>http://frescobaldi.org/images/frescobaldi1-en.png</image>
​    </screenshot>
​    <screenshot>
      <caption>Magnifier glass</caption>
​      <image>http://frescobaldi.org/images/magnifier1-small-en.png</image>
​    </screenshot>
    <screenshot>
      <caption>Snippet manager and editor</caption>
      <image>http://frescobaldi.org/images/snippet2-small-en.png</image>
    </screenshot>
​  </screenshots>
​
​  <url type="homepage">http://frescobaldi.org/</url>
​
​</component>

```

checked with `appstreamcli validate frescobaldi.appdata.xml` (which prints only a warning about the ID not being a reverse domain-name).

I realized that it's more complex than I thought, as I guess that a Makefile will be needed to install it in the installation prefix and to make it translatable. I'd better give up and let it to experienced developers.

**Comment by fedelibre** [comment]
This depends on issue #673.

When that is done (I'll try to work on it), I'll add the AppData file and possibly update the .desktop file so it can be translated.
I'll use the recommended DNS-reversed name (org.frescobaldi.Frescobaldi.desktop).

What about moving these files (*.appdata.xml, *.desktop) to a dedicated directory? Most projects I know use `desktop/` or `data/`.

**Comment by fedelibre** [comment]
> I'm trying to make a patch, just to see how it works (I'll probably have to leave it to some real developer). I cannot understand how to copy the `frescobaldi.appdata.xml` file to the proper install location. I've added this line to setup.py:
> 
> ```
> $ git diff
> diff --git a/setup.py b/setup.py
> index 9af67d7..bf9e834 100644
> --- a/setup.py
> +++ b/setup.py
> @@ -57,6 +57,7 @@ else:
>          ('share/icons/hicolor/scalable/apps', ['frescobaldi_app/icons/frescobaldi.svg']),
>          ('share/applications', ['frescobaldi.desktop']),
>          ('share/man/man1', ['frescobaldi.1']),
> +        ('share/metainfo/', ['frescobaldi.appdata.xml']),

The trailing slash here is a typo.

> 
> but then the file is copied to the python install directory, e.g. `/usr/lib/python3.5/site-packages/frescobaldi-3.0.0-py3.5.egg/share/metainfo/frescobaldi.appdata.xml`. But it should be relative to the install path, that is in /usr or /usr/local (or whatever is chosen by the user).

I was confused 2 years ago :-)
I guess the files are copied to the python install directory because they are present in the MANIFEST file. But they are also copied to the system directory (as defined in setup.py) when you run the right commands, e.g. `python3 setup.py bdist`.

I'll send a PR soon, after testing an installation:

```
 tree build/bdist.linux-x86_64/rpm/BUILDROOT/frescobaldi-3.0.1_git-1.x86_64/usr/share/
build/bdist.linux-x86_64/rpm/BUILDROOT/frescobaldi-3.0.1_git-1.x86_64/usr/share/
├── applications
│   └── frescobaldi.desktop
├── icons
│   └── hicolor
│       └── scalable
│           └── apps
│               └── frescobaldi.svg
├── man
│   └── man1
│       └── frescobaldi.1.gz
└── metainfo
    └── frescobaldi.appdata.xml
```

**Comment by fedelibre** [comment]
@wbsoft Would you be Ok with changing the ID of Linux .desktop file and icons to the reverse-DNS style: org.frescobaldi.Frescobaldi?

When submitting the PR to Flathub to distribute Frescobaldi as flatpak, I was told that the [current renaming of these files in the manifest should be eventually made upstream](https://github.com/flathub/flathub/pull/1277#pullrequestreview-323358177). This is not a blocker currently, but I think that it will be enforced in the future.

**Comment by wbsoft** [comment]
No problem! Probably needs also a change in setup.py, where it is listed and MANIFEST.in, where it is also listed for packaging.

**Comment by fedelibre** [comment]
@wbsoft I have a working patch ready and I'll send a PR soon.

On second thought, I think that using a `linux/` directory instead of `data/` directory would be more appropriate for a crossplatform application.

**Comment by fedelibre** [comment]
Don't know why this has not been closed automatically after the merge of the PR.. I'm closing it now.

BTW, 3.1.2 has reached Fedora repository, but the spec file did not include the metainfo file so I could not double-check that Frescobaldi can now be found in GNOME Software. I sent a [report to Fedora maintainer](https://bugzilla.redhat.com/show_bug.cgi?id=1829098).

**Comment by fedelibre** [comment]
Finally a GNOME Software user will be able to find Frescobaldi.
Tested on Fedora 32, [appstream-data-32-8.fc32](https://bodhi.fedoraproject.org/updates/FEDORA-2020-239dc4629a).

![Screenshot from 2020-08-07 22-11-11](https://user-images.githubusercontent.com/1644647/89684580-0a55af80-d8fb-11ea-87d8-fcef73d4a8d6.png)

![Screenshot from 2020-08-07 22-11-19](https://user-images.githubusercontent.com/1644647/89684620-16417180-d8fb-11ea-8ea2-8ed98174be6c.png)

![Screenshot from 2020-08-07 22-11-27](https://user-images.githubusercontent.com/1644647/89684629-1b9ebc00-d8fb-11ea-8037-9ca209a2bec7.png)

![Screenshot from 2020-08-07 22-11-44](https://user-images.githubusercontent.com/1644647/89684637-1fcad980-d8fb-11ea-835a-c01422d6dd83.png)
