### ISSUE TITLE
implement tile-based caching in qpageview (music/manuscript view)

### ISSUE THREAD

**Issue by wbsoft** [frescobaldi/frescobaldi#896]
The `qpageview` module I am currently working on is destined to replace `qpopplerview`. `qpageview` is more flexible, it supports a generic Page type, that can be a page from a poppler-supported (PDF) document, but also a SVG file or any other type of image/etc. Different Page types can be displayed together in a layout and scrollable viewer.

One of the problems with `qpopplerview` also needs to be adressed before `qpageview` can be considered ready: zooming in at large magnifications. Currently, qpopplerview always renders and caches a full page from a PDF, which becomes very memory-intensize at 400% and more for regular PDF files.

This will be solved by implementing tile-based rendering and caching for large images. Tiles will be fairly large, so that rendering pages at a moderate zoom doesn't need to be done in multiple parts.

**Comment by uliska** [comment]
@wbsoft I assume this can be closed?

**Comment by wbsoft** [comment]
Yes:)
