### ISSUE TITLE
Version of Qt 5

### ISSUE THREAD

**Issue by dliessi** [frescobaldi/frescobaldi#914]
Is the requirement of [Qt >= 5.4](https://github.com/wbsoft/frescobaldi/blob/master/INSTALL#L40) really a requirement or is Frescobaldi simply not tested for Qt5 < 5.4?

(The latest version of Qt 5 that could be compiled on Mac OS 10.6 was 5.3.x.
I'd like to have a working Frescobaldi 3 also on Mac OS 10.6, but I don't want to ask the maintainer of MacPorts' Qt 5 to invest time in providing Qt 5.3 if you already know that it wouldn't work.)

**Comment by uliska** [comment]
@dliessi is this still true today?

**Comment by dliessi** [comment]
Well, I gave up trying to support Frescobaldi 3 on older Mac systems. My current approach is to stick to the latest Frescobaldi 2 on those systems. Anyway I would still like to know whether Frescobaldi 3 can work with Qt <= 5.3.

**Comment by dliessi** [comment]
In the meantime, Qt 5.3 was added again to MacPorts.
On the other hand, Frescobaldi 3 now depends on QtWebEngine, which appeared in Qt 5.4, which does not build on Mac OS X 10.6 and earlier.

The conclusion is that users of old Mac systems will need to stick to Frescobaldi 2.

**Comment by uliska** [comment]
Another conclusion (also regarding Ubuntu 16.04 LTS) could be that we should find a way to support both for a few years.

**Comment by fedelibre** [comment]
@dliessi Can we close this issue?

As of today the [INSTALL file recommends Qt>= 5.9](https://github.com/frescobaldi/frescobaldi/blob/72c5493c7383cda8c255c17c16f570fff2adf842/INSTALL#L74).
